// src/pages/matter/widget/imageCache/ImageCacheList.tsx
import React from "react";
import { Button, Modal, Pagination, Space } from "antd";
import Pager from "../../../../common/model/base/Pager";
import ImageCache from "../../../../common/model/image/cache/ImageCache";
import TankComponent from "../../../../common/component/TankComponent";
import ImageCachePanel from "./ImageCachePanel";
import ImagePreviewer from "../../../widget/previewer/ImagePreviewer";
import MessageBoxUtil from "../../../../common/util/MessageBoxUtil";
import { ExclamationCircleFilled } from "@ant-design/icons";
import { Empty } from "antd";
import TankTitle from "../../../widget/TankTitle";
import Lang from "../../../../common/model/global/Lang";

interface IProps {
  initFilter: any;
}

interface IState {}

export default class ImageCacheList extends TankComponent<IProps, IState> {
  selectedImageCaches: ImageCache[] = [];
  pager = new Pager<ImageCache>(this, ImageCache, 2);

  constructor(props: IProps) {
    super(props);
    this.state = {};
  }

  componentDidMount() {
    this.refresh();
  }

  deleteBatch = () => {
    Modal.confirm({
      title: Lang.t("actionCanNotRevertConfirm"),
      icon: <ExclamationCircleFilled twoToneColor="#FFDC00" />,
      onOk: () => {
        const uuids = this.selectedImageCaches.map((i) => i.uuid).toString();
        const imageCache = new ImageCache();
        imageCache.httpDeleteBatch(uuids, () => {
          MessageBoxUtil.success(Lang.t("operationSuccess"));
          this.refresh();
        });
      },
    });
  };

  checkBatch = (check: boolean) => {
    this.pager.data.forEach((i) => {
      i.check = check;
    });
    this.checkImageCache();
  };

  refresh = () => {
    const { initFilter } = this.props;
    if (initFilter) {
      for (let key in initFilter) {
        if (initFilter.hasOwnProperty(key)) {
          this.pager.setFilterValue(key, initFilter[key]);
        }
      }
    }
    this.pager.page = 0;
    this.pager.httpList();
    this.selectedImageCaches = [];
  };

  checkImageCache = (imageCache?: ImageCache) => {
    if (imageCache) {
      if (imageCache.check) {
        this.selectedImageCaches.push(imageCache);
      } else {
        const index = this.selectedImageCaches.findIndex(
          (item) => item.uuid === imageCache.uuid
        );
        this.selectedImageCaches.splice(index, 1);
      }
    } else {
      this.selectedImageCaches.splice(0, this.selectedImageCaches.length);
      this.pager.data.forEach((imageCache) => {
        if (imageCache.check) {
          this.selectedImageCaches.push(imageCache);
        }
      });
    }
    this.updateUI();
  };

  previewImageCache = (imageCache: ImageCache) => {
    //从matter开始预览图片
    const imageArray: string[] = [];
    let startIndex = -1;
    this.pager.data.forEach((item) => {
      imageArray.push(item.getResizeUrl());
      if (item.uuid === imageCache.uuid) {
        startIndex = imageArray.length - 1;
      }
    });

    ImagePreviewer.showMultiPhoto(imageArray, startIndex);
  };

  changePage = (page: number) => {
    this.pager.page = page - 1; // page的页数0基
    this.pager.httpList();
    this.updateUI();
  };

  render() {
    const { selectedImageCaches, pager } = this;
    if (!pager.data.length) return <Empty description={Lang.t("matter.noImageCache")} />;
    return (
      <div>
        <TankTitle
          name={Lang.t("matter.imageCache")}
          children={
            <div>
              <Space>
                {selectedImageCaches.length ? (
                  <Button type="primary" onClick={this.deleteBatch}>
                    {Lang.t("delete")}
                  </Button>
                ) : null}
                {selectedImageCaches.length !== pager.data.length ? (
                  <Button type="primary" onClick={() => this.checkBatch(true)}>
                    {Lang.t("selectAll")}
                  </Button>
                ) : null}
                {pager.data.length &&
                selectedImageCaches.length === pager.data.length ? (
                  <Button type="primary" onClick={() => this.checkBatch(false)}>
                    {Lang.t("cancel")}
                  </Button>
                ) : null}
              </Space>
            </div>
          }
        />

        {pager.data.map((imageCache) => (
          <ImageCachePanel
            key={imageCache.uuid!}
            imageCache={imageCache}
            onDeleteSuccess={this.refresh}
            onCheckImageCache={this.checkImageCache}
            onPreviewImageCache={this.previewImageCache}
          />
        ))}

        <Pagination
          className="mt10 pull-right"
          onChange={this.changePage}
          current={pager.page + 1}
          total={pager.totalItems}
          pageSize={pager.pageSize}
          hideOnSinglePage
        />
      </div>
    );
  }
}

// src/backyard/image/cache/widget/ImageCacheList.vue
<template>
  <div class="widget-image-cache-list animated fadeIn">
    <div class="row">
      <div class="col-md-12 text-right pb10">
        <button class="btn btn-primary btn-sm " v-if="selectedImageCaches.length" @click.stop.prevent="deleteBatch">
          <i class="fa fa-trash"></i>
          {{ $t('delete') }}
        </button>
        <button class="btn btn-primary btn-sm" v-if="selectedImageCaches.length !== pager.data.length"
                @click.stop.prevent="checkAll">
          <i class="fa fa-check-square"></i>
          {{ $t('selectAll') }}
        </button>
        <button class="btn btn-primary btn-sm"
                v-if="pager.data.length && selectedImageCaches.length === pager.data.length"
                @click.stop.prevent="checkNone">
          <i class="fa fa-square-o"></i>
          {{ $t('cancel') }}
        </button>

      </div>

      <div class="col-md-12" v-for="(imageCache,index) in pager.data">
        <ImageCachePanel
          :imageCache="imageCache"
          @deleteSuccess="refresh"
          @checkImageCache="checkImageCache"
          @previewImageCache="previewImageCache"
        />
      </div>

      <div class="col-md-12 mt20">
        <NbPager :pager="pager" :callback="refresh"></NbPager>
      </div>

    </div>
  </div>
</template>

<script>
  import NbFilter from '../../../../common/widget/filter/NbFilter.vue'
  import NbPager from '../../../../common/widget/NbPager.vue'
  import Pager from '../../../../common/model/base/Pager'
  import ImageCache from "../../../../common/model/image/cache/ImageCache";
  import ImageCachePanel from "./ImageCachePanel"
  import {MessageBox, Message} from "element-ui"

  export default {

    data() {
      return {
        pager: new Pager(ImageCache, Pager.MAX_PAGE_SIZE),
        user: this.$store.state.user,
        selectedImageCaches: []
      }
    },
    props: {
      initFilter: {
        type: Object,
        required: false
      }
    },
    components: {
      NbFilter,
      NbPager,
      ImageCachePanel
    },
    methods: {
      search() {
        this.pager.page = 0
        this.refresh()
      },
      refresh() {

        if (this.initFilter) {
          for (let key in this.initFilter) {
            if (this.initFilter.hasOwnProperty(key)) {
              this.pager.setFilterValue(key, this.initFilter[key]);
            }
          }
        }
        this.pager.httpFastPage()
      },
      checkImageCache(imageCache) {

        let that = this
        //统计所有的勾选
        this.selectedImageCaches.splice(0, this.selectedImageCaches.length)
        this.pager.data.forEach(function (imageCache, index) {
          if (imageCache.check) {
            that.selectedImageCaches.push(imageCache)
          }
        })


      },
      //全选
      checkAll() {
        this.pager.data.forEach(function (i, index) {
          i.check = true
        })
        this.checkImageCache()
      },
      //取消全选
      checkNone() {
        this.pager.data.forEach(function (i, index) {
          i.check = false
        })

        this.checkImageCache()
      },
      previewImageCache(imageCache) {

        let that = this;

        //从matter开始预览图片
        let imageArray = []
        let startIndex = -1;
        this.pager.data.forEach(function (item, index) {
          imageArray.push(item.getResizeUrl())
          if (item.uuid === imageCache.uuid) {
            startIndex = imageArray.length - 1
          }
        })

        that.$photoSwipePlugin.showPhotos(imageArray, startIndex)

      },
      deleteBatch() {
        let that = this
        MessageBox.confirm(that.$t("actionCanNotRevertConfirm"), that.$t("prompt"), {
          confirmButtonText: that.$t("confirm"),
          cancelButtonText: that.$t("cancel"),
          type: 'warning',
          callback: function (action, instance) {
            if (action === 'confirm') {
              let uuids = ""
              that.selectedImageCaches.forEach(function (item, index) {
                if (index === 0) {
                  uuids = item.uuid
                } else {
                  uuids = uuids + "," + item.uuid
                }
              })
              let imageCache = new ImageCache()
              imageCache.httpDeleteBatch(uuids, function (response) {
                Message.success(that.$t("operationSuccess"))
                that.refresh()
              })
            }

          }
        })
      }
    },
    mounted() {
      this.pager.enableHistory()
      this.refresh()
    }
  }
</script>

<style lang="less" rel="stylesheet/less">
  .widget-image-cache-list {

  }
</style>
