// src/pages/share/Detail.tsx
import React from "react";
import TankComponent from "../../common/component/TankComponent";
import TankTitle from "../widget/TankTitle";
import { Button, Col, Empty, Input, Modal, Row, Space } from "antd";
import { RouteComponentProps } from "react-router";
import "./Detail.less";
import Share from "../../common/model/share/Share";
import Pager from "../../common/model/base/Pager";
import Matter from "../../common/model/matter/Matter";
import BrowserUtil from "../../common/util/BrowserUtil";
import SortDirection from "../../common/model/base/SortDirection";
import FrameLoading from "../widget/FrameLoading";
import Moon from "../../common/model/global/Moon";
import Sun from "../../common/model/global/Sun";
import MessageBoxUtil from "../../common/util/MessageBoxUtil";
import { ExclamationCircleFilled, DownloadOutlined, StopOutlined, LinkOutlined } from "@ant-design/icons";
import ShareDialogModal from "./widget/ShareDialogModal";
import DateUtil from "../../common/util/DateUtil";
import ShareMatterPanel from "./widget/ShareMatterPanel";
import BreadcrumbModel from "../../common/model/base/option/BreadcrumbModel";
import BreadcrumbPanel from "../widget/BreadcrumbPanel";
import ImagePreviewer from "../widget/previewer/ImagePreviewer";
import Lang from "../../common/model/global/Lang";

interface RouteParam {
  uuid: string;
}

interface IProps extends RouteComponentProps<RouteParam> {}

interface IState {}

export default class Detail extends TankComponent<IProps, IState> {
  // 默认分享详情中分页大小
  static sharePagerSize = 50;

  //当前面包屑模型数组。
  breadcrumbModels: BreadcrumbModel[] = [];

  // 是否需要提取码
  needShareCode = true;

  share = new Share(this);
  pager = new Pager<Matter>(this, Matter, Detail.sharePagerSize);
  user = Moon.getSingleton().user;

  constructor(props: IProps) {
    super(props);
  }

  componentDidMount(): void {
    this.share.uuid = this.props.match.params.uuid;
    //如果query中有rootUuid那么就更新.
    this.share.rootUuid =
      BrowserUtil.getQueryByName("shareRootUuid") || this.share.rootUuid;

    this.pager.enableHistory();
    this.refresh();
  }

  componentWillReceiveProps(nextProps: Readonly<IProps>, nextContext: any) {
    if (this.props.location.search !== nextProps.location.search) {
      this.pager.enableHistory();
      this.refresh();
    }
  }

  refresh = () => {
    const puuid = BrowserUtil.getQueryByName("puuid") || Matter.MATTER_ROOT;
    this.share.httpBrowse(puuid, this.share.rootUuid, () => {
      if (puuid === Matter.MATTER_ROOT) {
        this.pager.clear();
        this.pager.totalItems = this.share.matters.length;
        this.pager.data = this.share.matters;
      }

      //刷新面包屑
      this.refreshBreadcrumbs();

      this.needShareCode = false;
      this.updateUI();
    });

    this.refreshMatterPager();
  };

  refreshMatterPager = () => {
    //只有当鉴权通过，并且不是分享根目录时需要才去进行page请求，根目录下matters已经通过browse接口拿到了
    const puuid = BrowserUtil.getQueryByName("puuid");
    if (!this.needShareCode && puuid && puuid !== Matter.MATTER_ROOT) {
      const {
        uuid: shareUuid,
        code: shareCode,
        rootUuid: shareRootUuid,
      } = this.share;
      this.pager.setFilterValues({
        puuid,
        shareUuid,
        shareCode,
        shareRootUuid,
        orderCreateTime: SortDirection.DESC, // 默认以时间降序
        orderDir: SortDirection.DESC, // 默认文件夹排在前面
      });
      this.pager.httpList();
    }
  };

  getFiles = (value: string) => {
    this.share.code = value;
    this.refresh();
  };

  downloadZip = () => {
    const puuid = BrowserUtil.getQueryByName("puuid") || Matter.MATTER_ROOT;
    this.share.downloadZip(puuid);
  };

  cancelShare = () => {
    Modal.confirm({
      title: Lang.t("share.cancelPrompt"),
      icon: <ExclamationCircleFilled twoToneColor="#FFDC00" />,
      onOk: () => {
        this.share.httpDel(() => {
          MessageBoxUtil.success(Lang.t("operationSuccess"));
          Sun.navigateTo("/share/list");
        });
      },
    });
  };

  previewImage = (matter: Matter) => {
    let imageArray: string[] = [];
    let startIndex = -1;
    const { share } = this;
    this.pager.data.forEach((item) => {
      if (item.isImage()) {
        imageArray.push(item.getSharePreviewUrl(share.uuid!, share.code!, share.rootUuid));
        if (item.uuid === matter.uuid) {
          startIndex = imageArray.length - 1;
        }
      }
    });

    ImagePreviewer.showMultiPhoto(imageArray, startIndex);
  };

  goToDirectory = (id?: string) => {
    const paramId = this.props.match.params.uuid;

    if (id) {
      //share.rootUuid 一旦设置好了，只要根文件夹不换，那么就一直不会变。
      const puuid = BrowserUtil.getQueryByName("puuid");
      if (!puuid || puuid === Matter.MATTER_ROOT) {
        this.share.rootUuid = id;
        this.pager.clear();
      }

      this.pager.setFilterValue("puuid", id);
      this.pager.page = 0;
      const query = this.pager.getParams();
      Sun.navigateQueryTo({ path: `/share/detail/${paramId}`, query });
    } else {
      // 回到分享根目录，先将rootUuid交给根目录
      this.share.rootUuid = Matter.MATTER_ROOT;
      this.pager.clear();
      Sun.navigateQueryTo({ path: `/share/detail/${paramId}` });
    }
  };

  refreshBreadcrumbs = () => {
    let that = this;

    //清空
    that.breadcrumbModels = [];

    that.breadcrumbModels.push({
      name: Lang.t("layout.allFiles"),
      path: "/share/detail/" + this.share.uuid,
      query: {},
      displayDirect: false,
    });

    let pMatter = this.share.dirMatter;
    while (pMatter && pMatter.uuid) {
      //插入到最前面
      let query = this.pager.getParams();
      query["puuid"] = pMatter.uuid;
      that.breadcrumbModels.splice(1, 0, {
        name: pMatter.name,
        path: "/share/detail/" + this.share.uuid,
        query: query,
        displayDirect: false,
      });
      pMatter = pMatter.parent!;
    }
  };

  render() {
    const { share, needShareCode, user, pager } = this;

    console.log(share);

    if (share.detailLoading && needShareCode) return <FrameLoading />;
    return (
      <div className="share-detail">
        <TankTitle name={Lang.t("share.shareDetail")} />
        {needShareCode ? (
          <div>
            <Row>
              <Col span={12} offset={6} className="mt100">
                <Input.Search
                  placeholder={Lang.t("share.enterCode")}
                  enterButton={Lang.t("share.getFiles")}
                  size="large"
                  onSearch={this.getFiles}
                />
              </Col>
            </Row>
          </div>
        ) : (
          <div>
            <div className="share-block">
              <div className="upper">
                <div className="left-box">
                  <img className="share-icon" src={share.getIcon()} />
                  <span className="name">
                    {share.name}
                    {share.hasExpired() ? (
                      <span className="text-danger">
                        {Lang.t("share.expired")}
                      </span>
                    ) : null}
                  </span>
                </div>
                <div className="right-box">
                  <Space>
                    <Button type="primary" onClick={this.downloadZip}>
                      <DownloadOutlined />
                      {Lang.t("download")}
                    </Button>
                    {user.uuid && user.uuid === share.userUuid ? (
                      <>
                        <Button danger onClick={this.cancelShare}>
                          <StopOutlined />
                          {Lang.t("share.cancelShare")}
                        </Button>
                        <Button
                          type="primary"
                          onClick={() => ShareDialogModal.open(share)}
                        >
                          <LinkOutlined />
                          {Lang.t("share.getLink")}
                        </Button>
                      </>
                    ) : null}
                  </Space>
                </div>
              </div>
              <div className="share-info">
                <Space>
                  <span>
                    {Lang.t("share.sharer")}: {share.username}
                  </span>
                  <span>
                    {Lang.t("createTime")}:{" "}
                    {DateUtil.simpleDateHourMinute(share.createTime)}
                  </span>
                  <span>
                    {share.expireInfinity
                      ? Lang.t("share.noExpire")
                      : `${Lang.t(
                          "share.expireTime"
                        )}：${DateUtil.simpleDateHourMinute(share.expireTime)}`}
                  </span>
                </Space>
              </div>
            </div>

            <div className="breadcrumb-area">
              <BreadcrumbPanel breadcrumbModels={this.breadcrumbModels} />
            </div>

            {pager.data.length ? (
              pager.data.map((matter) => (
                <ShareMatterPanel
                  key={matter.uuid!}
                  matter={matter}
                  share={share}
                  onGoToDirectory={this.goToDirectory}
                  onPreviewImage={this.previewImage}
                />
              ))
            ) : (
              <Empty description={Lang.t("share.noContent")} />
            )}
          </div>
        )}
      </div>
    );
  }
}

// src/backyard/share/Detail.vue
<template>
  <div class="share-detail">

    <LoadingFrame :loading="share.detailLoading && needShareCode">
      <div v-if="!needShareCode">
        <div class="share-block">
          <div class="upper">
            <div class="left-box">
              <img class="share-icon" :src="share.getIcon()"/>
              <span class="name">
                {{share.name}}
                <span class="text-danger" v-if="share.hasExpired()">{{$t('share.expired')}}</span>
              </span>
            </div>
            <div class="right-box">

              <button class="btn btn-primary btn-sm mr5" @click.stop.prevent="downloadZip">
                <i class="fa fa-download"></i>
                {{$t('download')}}
              </button>

              <button class="btn btn-danger btn-sm mr5" @click.stop.prevent="cancelShare"
                      v-if="user.uuid && user.uuid === share.userUuid">
                <i class="fa fa-ban"></i>
                {{$t('share.cancelShare')}}
              </button>

              <button class="btn btn-primary btn-sm mr5" @click.stop.prevent="shareDialogVisible = true"
                      v-if="user.uuid && user.uuid === share.userUuid">
                <i class="fa fa-link"></i>
                {{$t('share.getLink')}}
              </button>
              <el-dialog
                :title="$t('share.shareDetail')"
                :visible.sync="shareDialogVisible"
                :append-to-body="true">
                <ShareDialogPanel :share="share"/>
                <span slot="footer" class="dialog-footer">
                <button class="btn btn-primary btn-sm mr5" @click="share.copyLinkAndCode()">{{$t('share.copyLinkAndCode')}}</button>
                <button class="btn btn-default btn-sm mr5" @click="shareDialogVisible = false">{{$t('close')}}</button>
              </span>
              </el-dialog>

            </div>
          </div>
          <div class="share-info">

        <span class="inline-block mr10">
          {{$t('share.sharer')}}:{{share.username}}
        </span>
            <span class="inline-block mr10">
          {{$t('createTime')}}:{{share.createTime | simpleDateHourMinute}}
        </span>
            <span class="inline-block mr10" v-if="!share.expireInfinity">
          {{$t('share.expireTime')}}:{{share.expireTime | simpleDateHourMinute}}
        </span>
            <span class="inline-block mr10" v-if="share.expireInfinity">
          {{$t('share.noExpire')}}
        </span>

          </div>
        </div>

        <div class="breadcrumb" v-if="breadcrumbs && breadcrumbs.length">
          <a href="javascript:void(0)"
             @click.stop.prevent="goToDirectory(null)">{{$t('share.allFiles')}}</a>
          <span v-for="(matter,index) in breadcrumbs">
          <span>/</span>
          <a v-if="index<breadcrumbs.length-1" href="javascript:void(0)" @click.stop.prevent="goToDirectory(matter)">{{matter.name}} </a>
          <span v-if="index===breadcrumbs.length-1">{{matter.name}}</span>
        </span>
        </div>

        <div v-for="matter in pager.data">
          <ShareMatterBar
            :matter="matter"
            :share="share"
            @goToDirectory="goToDirectory"
          />
        </div>

        <div class="mt20">
          <NbPager :pager="pager" :callback="refresh" :emptyHint="$t('share.noContent')"/>
        </div>
      </div>

      <div v-if="needShareCode" class="col-md-4 col-md-offset-4 mt100">
        <div class="input-group">
          <input type="text" class="form-control" :placeholder="$t('share.enterCode')" v-model="share.code"
                 @keyup.enter="refresh">
          <span class="input-group-btn">
          <button type="button" class="btn btn-primary" @click.stop.prevent="refresh">
            {{$t('share.getFiles')}}
          </button>
        </span>
        </div>
      </div>
    </LoadingFrame>

  </div>
</template>

<script>

  import Share from "../../common/model/share/Share";
  import ShareMatterBar from "./widget/ShareMatterBar"
  import Matter from "../../common/model/matter/Matter";
  import Pager from "../../common/model/base/Pager";
  import NbPager from "../../common/widget/NbPager";
  import {SortDirection} from "../../common/model/base/SortDirection";
  import {Message, MessageBox} from 'element-ui'
  import ShareDialogPanel from "./widget/ShareDialogPanel"
  import LoadingFrame from "../widget/LoadingFrame";
  import {ResultCode} from "../../common/model/base/ResultCode";

  export default {
    data() {
      return {
        needShareCode: true,
        shareDialogVisible: false,
        breadcrumbs: [],
        share: new Share(),
        pager: new Pager(Matter, 50),
        user: this.$store.state.user,
        preference: this.$store.state.preference
      }
    },
    computed: {},
    watch: {
      '$route'(newVal, oldVal) {

        this.refresh()
      }

    },
    methods: {
      goToDirectory(dirMatter) {

        //如果dirMatter不存在，那么当成回到分享详情页处理
        if (dirMatter) {

          let puuid = this.$route.query.puuid

          this.pager.setFilterValue('puuid', dirMatter.uuid)
          this.pager.page = 0
          let query = this.pager.getParams()

          //share.rootUuid 一旦设置好了，只要根文件夹不换，那么就一直不会变。
          if (!puuid || puuid === Matter.MATTER_ROOT) {
            this.share.rootUuid = dirMatter.uuid
            this.pager.clear()
          }

          //采用router去管理路由
          this.$router.push({
            path: this.$route.path,
            query: query
          })

        } else {

          this.share.rootUuid = Matter.MATTER_ROOT
          this.pager.clear()


          //采用router去管理路由
          this.$router.push({
            path: this.$route.path,
            query: {}
          })
        }


      },
      refreshPager() {

        let that = this
        let puuid = this.$route.query.puuid

        //只有当鉴权通过，并且不是分享首页时需要去进行page请求。
        if (!that.needShareCode && puuid && puuid !== Matter.MATTER_ROOT) {

          this.pager.setFilterValue('puuid', puuid)
          this.pager.setFilterValue('shareUuid', that.share.uuid)
          this.pager.setFilterValue('shareCode', that.share.code)
          this.pager.setFilterValue('shareRootUuid', that.share.rootUuid)

          //如果所有的排序都没有设置，那么默认以时间降序。
          this.pager.setFilterValue('orderCreateTime', SortDirection.DESC)
          this.pager.setFilterValue("orderDir", SortDirection.DESC)

          this.pager.httpFastPage()
        }

      },
      refresh() {

        let that = this
        let puuid = this.$route.query.puuid

        if (!puuid) {
          puuid = Matter.MATTER_ROOT
        }

        that.share.httpBrowse(puuid, that.share.rootUuid, function (response) {

          //如果是寻根之旅，那么直接赋值到pager.
          if (puuid === Matter.MATTER_ROOT) {
            that.pager.page = 0
            that.pager.pageSize = 50
            that.pager.totalItems = that.share.matters.length
            that.pager.data.splice(0, that.pager.data.length)
            that.pager.data.push(...that.share.matters)
          }

          //刷新面包屑
          that.refreshBreadcrumbs()


          if (that.needShareCode) {
            that.needShareCode = false
            that.refreshPager()
          }

        }, function (errorMessage, response) {

          if (response.data.code === ResultCode.NEED_SHARE_CODE) {
            that.needShareCode = true
            that.$message.warning(that.$t('share.enterCode'))
          } else if (response.data.code === ResultCode.SHARE_CODE_ERROR) {
            that.needShareCode = true
            that.$message.error(that.$t('share.codeError'))
          } else {
            that.$message.error(errorMessage)
          }

        })


        that.refreshPager()

      },
      refreshBreadcrumbs() {
        let that = this

        //清空
        that.breadcrumbs.splice(0, that.breadcrumbs.length)

        let pMatter = this.share.dirMatter
        while (pMatter && pMatter.uuid) {
          that.breadcrumbs.splice(0, 0, pMatter)
          pMatter = pMatter.parent
        }

      },
      cancelShare() {
        let that = this
        MessageBox.confirm(that.$t('share.cancelPrompt'), that.$t('prompt'), {
          confirmButtonText: that.$t("confirm"),
          cancelButtonText: that.$t("cancel"),
          type: 'warning',
          callback: function (action, instance) {
            if (action === 'confirm') {
              that.share.httpDelete(function (response) {
                Message.success(that.$t('operationSuccess'))
                that.$router.push("/share/list")

              })
            }

          }
        })

      },
      downloadZip() {
        let puuid = this.$route.query.puuid

        if (!puuid) {
          puuid = Matter.MATTER_ROOT
        }

        this.share.downloadZip(puuid)

      }
    },
    components: {
      LoadingFrame,
      ShareDialogPanel,
      ShareMatterBar,
      NbPager
    },
    mounted() {
      let that = this;

      this.share.uuid = this.$store.state.route.params.uuid
      //如果query中有rootUuid那么就更新.
      if (this.$route.query.shareRootUuid) {
        this.share.rootUuid = this.$route.query.shareRootUuid
      }

      this.pager.enableHistory()

      this.refresh()

    }
  }
</script>

<style lang="less" rel="stylesheet/less">
  .share-detail {

    .share-block {
      background-color: white;
      padding: 30px 10px 20px 10px;

      .upper {

        //宽屏flex布局
        display: block;
        @media (min-width: 992px) {
          display: flex;
          justify-content: space-between;
        }

        .left-box {
          margin-bottom: 15px;
          display: block;
          @media (min-width: 992px) {
            display: flex;
            justify-content: space-between;
            align-content: center;
          }

          .share-icon {
            width: 30px;
            height: 30px;
          }

          .name {
            font-size: 18px;
            margin-left: 10px;
            line-height: 30px;
          }
        }
      }

      .share-info {
        margin-top: 5px;
      }
    }

    .breadcrumb {
      padding: 10px;
      border-top: 1px solid #eee;

    }

  }
</style>
