// src/pages/user/List.tsx
import React from 'react';
import {Link, RouteComponentProps} from 'react-router-dom';
import './List.less';
import SortDirection from '../../common/model/base/SortDirection';
import Pager from '../../common/model/base/Pager';
import StringUtil from '../../common/util/StringUtil';
import FileUtil from '../../common/util/FileUtil';
import DateUtil from '../../common/util/DateUtil';
import FilterPanel from '../widget/filter/FilterPanel';
import TableEmpty from '../widget/TableEmpty';
import User from "../../common/model/user/User";
import TankComponent from "../../common/component/TankComponent";
import TankTitle from "../widget/TankTitle";
import {ColumnProps} from 'antd/lib/table';
import {Table, Button, Modal, Tag, Tooltip} from "antd";
import {CheckCircleOutlined, PlusOutlined, StopOutlined, UserSwitchOutlined} from '@ant-design/icons';
import {UserRoleMap} from "../../common/model/user/UserRole";
import {UserStatus, UserStatusMap} from "../../common/model/user/UserStatus";
import {DeleteOutlined, EditOutlined, ExclamationCircleFilled} from "@ant-design/icons/lib";
import MessageBoxUtil from "../../common/util/MessageBoxUtil";
import Color from "../../common/model/base/option/Color";
import TransfigurationModal from "./widget/TransfigurationModal";
import Lang from "../../common/model/global/Lang";
import Moon from "../../common/model/global/Moon";


interface IProps extends RouteComponentProps {

}

interface IState {

}


export default class List extends TankComponent<IProps, IState> {

  //获取分页的一个帮助器
  pager: Pager<User> = new Pager<User>(this, User, 10);

  constructor(props: IProps) {
    super(props);

    this.state = {};
  }


  componentDidMount() {

    //刷新一下列表
    let that = this;

    that.pager.enableHistory();

    that.refresh();
  }

  search() {
    let that = this;
    that.pager.page = 0;
    that.refresh();
  }

  refresh() {

    let that = this;

    //如果没有任何的排序，默认使用时间倒序
    if (!that.pager.getCurrentSortFilter()) {
      that.pager.setFilterValue('orderCreateTime', SortDirection.DESC);
    }

    that.pager.httpList();
  }

  toggleStatus(user: User) {
    let that = this
    user.httpToggleStatus(function () {
      MessageBoxUtil.success(Lang.t("operationSuccess"))
      that.updateUI()
    })
  }


  delete(user: User) {
    let that = this
    Modal.confirm({
      title: Lang.t("user.deleteHint", user.username),
      icon: <ExclamationCircleFilled twoToneColor={Color.WARNING}/>,
      onOk: () => {
        user.httpDel(function () {
          MessageBoxUtil.success(Lang.t("operationSuccess"))
          that.refresh()
        })
      },
    });

  }


  transfiguration(user: User) {

    let that = this
    TransfigurationModal.open(user)

  }


  render() {

    let that = this;

    //router中传入的路由相关对象
    let match = this.props.match;

    //pager对象
    let pager = this.pager;

    let user: User = Moon.getSingleton().user

    const columns: ColumnProps<User>[] = [{
      title: Lang.t("user.avatar"),
      dataIndex: 'avatarUrl',
      render: (text: any, record: User, index: number): React.ReactNode => (
        <Link to={StringUtil.prePath(match.path) + '/detail/' + record.uuid}>
          <img alt="avatar" className='avatar-small cursor' src={record.getAvatarUrl()}/>
        </Link>
      ),
    }, {
      title: Lang.t("user.username"),
      dataIndex: 'username',
      render: (text: any, record: User, index: number): React.ReactNode => {
        return <div>
          <div>
            <Link to={StringUtil.prePath(match.path) + '/detail/' + record.uuid}>{record.username}</Link>
          </div>
          {
            user.uuid === record.uuid && (
              <div className="text-danger">(It's you)</div>
            )
          }
        </div>
      },
    }, {
      title: Lang.t("user.role"),
      dataIndex: 'role',
      render: (text: any, record: User, index: number): React.ReactNode => (
        <Tag color={UserRoleMap[record.role].color}>{UserRoleMap[record.role].name}</Tag>
      ),
    }, {
      title: Lang.t("user.singleFileSizeLimit"),
      dataIndex: 'sizeLimit',
      render: (text: any, record: User, index: number): React.ReactNode => (
        <span>{FileUtil.humanFileSize(record.sizeLimit)}</span>
      ),
    }, {
      title: Lang.t("user.totalFileSize"),
      dataIndex: 'totalSize',
      render: (text: any, record: User, index: number): React.ReactNode => (
        <span>{FileUtil.humanFileSize(record.totalSize)}</span>
      ),
    }, {
      title: Lang.t("user.totalFileSizeLimit"),
      dataIndex: 'totalSizeLimit',
      render: (text: any, record: User, index: number): React.ReactNode => (
        <span>{FileUtil.humanFileSize(record.totalSizeLimit)}</span>
      ),
    }, {
      title: Lang.t("user.status"),
      dataIndex: 'status',
      render: (text: any, record: User, index: number): React.ReactNode => (
        <Tag color={UserStatusMap[record.status].color}>{UserStatusMap[record.status].name}</Tag>
      ),
    }, {
      title: Lang.t("user.lastLogin"),
      dataIndex: 'lastTime',
      render: (text: any, record: User, index: number): React.ReactNode => (
        <div>
          <div>{record.lastIp}</div>
          <div>{DateUtil.simpleDateTime(record.lastTime)}</div>
        </div>
      ),
    }, {
      title: Lang.t("createTime"),
      dataIndex: 'createTime',
      sorter: true,
      sortOrder: pager.getDefaultSortOrder('createTime'),
      sortDirections: [SortDirection.DESCEND, SortDirection.ASCEND],
      render: (text: any, record: User, index: number): React.ReactNode => (
        DateUtil.simpleDateTime(text)
      ),
    }, {
      title: Lang.t("operation"),
      dataIndex: 'action',
      render: (text: any, record: User) => (
        <span>

          <Link title={Lang.t("edit")}
                to={StringUtil.prePath(match.path) + '/edit/' + record.uuid}>
            <Tooltip title={Lang.t("edit")}>
              <EditOutlined className="btn-action"/>
            </Tooltip>
          </Link>

          {
            record.status === UserStatus.OK && record.uuid !== user.uuid && (
              <Tooltip title={Lang.t("user.disableUser")}>
                <StopOutlined className="btn-action" style={{color: Color.DANGER}}
                              onClick={this.toggleStatus.bind(this, record)}/>
              </Tooltip>
            )
          }

          {
            record.status === UserStatus.DISABLED && record.uuid !== user.uuid && (
              <Tooltip title={Lang.t("user.activeUser")}>
                <CheckCircleOutlined className="btn-action" style={{color: Color.SUCCESS}}
                                     onClick={this.toggleStatus.bind(this, record)}/>
              </Tooltip>
            )
          }

          {
            record.status === UserStatus.DISABLED && record.uuid !== user.uuid && (
              <Tooltip title={Lang.t("user.deleteUser")}>
                <DeleteOutlined className="btn-action" style={{color: Color.DANGER}}
                                onClick={this.delete.bind(this, record)}/>
              </Tooltip>
            )
          }

          {
            record.uuid !== user.uuid && (
              <Tooltip title={Lang.t("user.transfiguration")}>
                <UserSwitchOutlined className="btn-action" style={{color: Color.PRIMARY}}
                                    onClick={this.transfiguration.bind(this, record)}/>
              </Tooltip>
            )
          }




        </span>
      ),
    }];

    return (
      <div className="page-user-list">

        <TankTitle name={Lang.t("layout.users")}>
          <Link to={'/user/create'}>
            <Button type={"primary"} icon={<PlusOutlined/>}>{Lang.t("user.createUser")}</Button>
          </Link>
        </TankTitle>

        <div>
          <FilterPanel filters={pager.filters} onChange={this.search.bind(this)}/>
        </div>
        <Table
          rowKey="uuid"
          loading={pager.loading}
          dataSource={pager.data}
          columns={columns}
          pagination={pager.getPagination()}
          onChange={pager.tableOnChange.bind(pager)}
          locale={{emptyText: (<TableEmpty pager={pager} onRefresh={this.refresh.bind(this)}/>)}}
        />
      </div>
    );
  }
}

// src/backyard/user/List.vue
<template>
  <div class="backyard-user-list animated fadeIn">
    <div class="row">

      <div class="col-md-12">
        <NbPlainFilter :filters="pager.filters" @change="search"/>
      </div>

      <div class="col-md-12" v-for="(userItem,index) in pager.data">
        <div class="bg-white border br4 p10 mb10">
          <div class="media">
            <div class="pull-left">
              <router-link :to="'/user/detail/'+userItem.uuid">
                <img class="img-circle img-md" :src="userItem.getAvatarUrl()">
              </router-link>
            </div>
            <div class="media-body">
              <div>
							<span class="f16">
								<router-link class="black" :to="'/user/detail/'+userItem.uuid">
                  <span>
                    {{userItem.username}}
                    <span v-if="userItem.status === UserStatus.DISABLED"
                          class="label label-danger">{{$t('user.disabled')}}</span>
                  </span>

										<span v-if="userItem.uuid === user.uuid"
                          class="text-danger">(It's you)</span>
								</router-link>
							</span>
              </div>
              <div>
                <div :class="'mt5 text-'+UserRoleMap[userItem.role].style">
                  {{$t(UserRoleMap[userItem.role].name)}}
                </div>
              </div>
              <div class="mv5 text-muted one-line">
                {{userItem.description}}
              </div>
              <div class="mv5">
                <span class="mr10">
                  {{$t('user.singleFileSizeLimit')}}:
                    <span v-if="userItem.sizeLimit >= 0">
                            {{userItem.sizeLimit | humanFileSize}}
                          </span>
                    <span v-else>
                            {{$t('user.noLimit')}}
                          </span>
                </span>
                <span class="mr10">
                  {{$t('user.totalFileSizeLimit')}}:
                    <span v-if="userItem.totalSizeLimit >= 0">
                            {{userItem.totalSizeLimit | humanFileSize}}
                          </span>
                    <span v-else>
                            {{$t('user.noLimit')}}
                          </span>
                </span>
                <span class="mr10">
                  {{$t('user.totalFileSize')}}:
                    <span>
                            {{userItem.totalSize | humanFileSize}}
                          </span>
                </span>

              </div>
              <div class="mv5">
                <span class="mr10">{{$t('user.lastLoginTime')}}: {{userItem.lastTime | humanTime}}</span>
                <span class="mr10">{{$t('user.lastLoginIp')}}: {{userItem.lastIp}}</span>

                <span class="pull-right action-buttons">

                  <router-link :to="'/user/edit/'+userItem.uuid" :title="$t('edit')">
										<i class="fa fa-pencil text-info f18"></i>
									</router-link>

									<a href="javascript:void(0)"
                     :title="$t('user.transfiguration')" @click.stop.prevent="userItem.transfiguration()">
                    <i class="fa fa-user-secret f18"></i>
									</a>

									<a href="javascript:void(0)"
                     v-if="user.role === UserRole.ADMINISTRATOR && userItem.status === UserStatus.OK && user.uuid!==userItem.uuid"
                     :title="$t('user.disableUser')" @click.stop.prevent="toggleStatus(userItem)">
                    <i class="fa fa-close text-danger f18"></i>
									</a>
                  <a href="javascript:void(0)"
                     v-if="user.role === UserRole.ADMINISTRATOR && userItem.status === UserStatus.DISABLED && user.uuid!==userItem.uuid"
                     :title="$t('user.activeUser')" @click.stop.prevent="toggleStatus(userItem)">
                    <i class="fa fa-check text-success f18"></i>
									</a>

							</span>

              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-12 mt20">
        <NbPager :pager="pager" :callback="refresh"></NbPager>
      </div>

    </div>
  </div>
</template>

<script>
  import NbPlainFilter from '../../common/widget/filter/NbPlainFilter.vue'
  import NbPager from '../../common/widget/NbPager.vue'
  import Pager from '../../common/model/base/Pager'
  import User from '../../common/model/user/User'
  import {UserRole, UserRoleList, UserRoleMap} from "../../common/model/user/UserRole";
  import {UserStatus, UserStatusList, UserStatusMap} from "../../common/model/user/UserStatus";
  import {handleImageUrl} from "../../common/util/ImageUtil";

  export default {

    data() {
      return {
        UserRole,
        UserRoleList,
        UserRoleMap,
        UserStatus,
        UserStatusList,
        UserStatusMap,

        pager: new Pager(User),
        user: this.$store.state.user
      }
    },
    components: {
      NbPlainFilter,
      NbPager
    },
    methods: {
      handleImageUrl,
      search() {
        this.pager.page = 0
        this.refresh()
      },
      refresh() {
        this.pager.httpFastPage()
      },
      toggleStatus(user) {
        let that = this
        user.httpToggleStatus(function () {
          that.refresh()
        })
      }
    },
    mounted() {
      this.pager.enableHistory()
      this.refresh()
    }
  }
</script>

<style lang="less" rel="stylesheet/less">
  .backyard-user-list {

  }
</style>
