// src/pages/preference/Index.tsx
import React from 'react';
import {Link, RouteComponentProps} from "react-router-dom";
import "./Index.less"
import TankComponent from "../../common/component/TankComponent";
import User from "../../common/model/user/User";
import Moon from "../../common/model/global/Moon";
import TankTitle from "../widget/TankTitle";
import {Button} from "antd";
import {EditOutlined} from '@ant-design/icons';
import InfoCell from "../widget/InfoCell";
import Preference from "../../common/model/preference/Preference";
import TankContentCard from '../widget/TankContentCard';
import FileUtil from "../../common/util/FileUtil";
import ImagePreviewer from "../widget/previewer/ImagePreviewer";
import Lang from "../../common/model/global/Lang";


interface IProps extends RouteComponentProps {

}

interface IState {

}

export default class Index extends TankComponent<IProps, IState> {

  user: User = Moon.getSingleton().user

  preference: Preference = Moon.getSingleton().preference

  constructor(props: IProps) {
    super(props);

    this.state = {};
  }

  componentDidMount() {

    this.refresh()

  }

  //refresh preference.
  refresh() {
    let that = this

    that.preference.httpFetch(function () {
      that.updateUI()

    })
  }

  render() {

    let that = this

    return (
      <div className="page-preference-index">
        <TankTitle name={Lang.t("layout.setting")}>
          <Link to={'/preference/edit'}>
            <Button type={"primary"} icon={<EditOutlined/>}>{Lang.t("edit")}</Button>
          </Link>
        </TankTitle>

        <TankContentCard>
          <InfoCell name={Lang.t("preference.websiteName")}>
            {this.preference.name}
          </InfoCell>

          <InfoCell name={Lang.t("preference.logo")}>
            {this.preference.logoUrl && (
              <img src={this.preference.logoUrl} alt="logo"
                   className="img-logo" onClick={() => {
                ImagePreviewer.showSinglePhoto(this.preference.logoUrl!)
              }}/>
            )}
          </InfoCell>

          <InfoCell name={'favicon'}>
            {this.preference.faviconUrl && (
              <img src={this.preference.faviconUrl} alt="logo"
                   className="img-favicon" onClick={() => {
                ImagePreviewer.showSinglePhoto(this.preference.faviconUrl!)
              }}/>
            )}
          </InfoCell>

          <InfoCell name={Lang.t("preference.copyright")}>
            <span dangerouslySetInnerHTML={{__html: this.preference.copyright}}/>

          </InfoCell>

          <InfoCell name={Lang.t("preference.extraInfo")}>
            <span dangerouslySetInnerHTML={{__html: this.preference.record}}/>
          </InfoCell>

          <InfoCell name={Lang.t("preference.zipMaxNumLimit")}>
            {this.preference.downloadDirMaxNum === -1 ? Lang.t("preference.noLimit") : this.preference.downloadDirMaxNum}
          </InfoCell>

          <InfoCell name={Lang.t("preference.zipMaxSizeLimit")}>
            {FileUtil.humanFileSize(this.preference.downloadDirMaxSize)}
          </InfoCell>

          <InfoCell name={Lang.t("preference.userDefaultSizeLimit")}>
            {FileUtil.humanFileSize(this.preference.defaultTotalSizeLimit)}
          </InfoCell>

          <InfoCell name={Lang.t("preference.allowRegister")}>
            {this.preference.allowRegister ? Lang.t("yes") : Lang.t("no")}
          </InfoCell>

          <InfoCell name={Lang.t("preference.docLink")}>
            <a href={'https://tank-doc.eyeblue.cn/zh'} target="_blank">
              https://tank-doc.eyeblue.cn/zh
            </a>
          </InfoCell>


        </TankContentCard>

      </div>
    );
  }
}

// src/views/preference/Index.vue
<template>
  <div class="backyard-preference">

    <div class="preference-block tank-box">
      <div class="row">
        <div class="col-md-12 form-info">
          <span>{{$t('preference.websiteName')}}: </span>
          <span class="bold">{{preference.name}}</span>
        </div>

        <div class="col-md-12 form-info">
          <span>{{$t('preference.logo')}}: </span>
          <span>
            <img v-if="preference.logoUrl" :src="preference.logoUrl" alt="logo" class="max-height-100">
          </span>
        </div>

        <div class="col-md-12 form-info">
          <span>favicon: </span>
          <span>
            <img v-if="preference.faviconUrl" :src="preference.faviconUrl" alt="favicon" class="max-height-100">
          </span>
        </div>

        <div class="col-md-12 form-info">
          <span>{{$t('preference.copyright')}}: </span>
          <span v-html="preference.copyright"></span>
        </div>

        <div class="col-md-12 form-info">
          <span>{{$t('preference.extraInfo')}}: </span>
          <span v-html="preference.record"></span>
        </div>

        <div class="col-md-12 form-info">
          <span>{{$t('preference.zipMaxNumLimit')}}: </span>
          <span v-html="preference.downloadDirMaxNum"></span>
        </div>

        <div class="col-md-12 form-info">
          <span>{{$t('preference.allowRegister')}}: </span>
          <span>{{preference.allowRegister?$t('yes'):$t('no')}}</span>
        </div>

        <div class="col-md-12 form-info">
          <span>{{$t('preference.zipMaxSizeLimit')}}: </span>
          <span>
            <span class="mr10">
                    <span v-if="preference.downloadDirMaxSize >= 0">
                            {{preference.downloadDirMaxSize | humanFileSize}}
                          </span>
                    <span v-else>
                            {{$t('preference.noLimit')}}
                          </span>
                </span>
          </span>
        </div>

        <div class="col-md-12 form-info">
          <span>{{$t('preference.userDefaultSizeLimit')}}: </span>
          <span>
            <span class="mr10">
                    <span v-if="preference.defaultTotalSizeLimit >= 0">
                            {{preference.defaultTotalSizeLimit | humanFileSize}}
                          </span>
                    <span v-else>
                            {{$t('preference.noLimit')}}
                          </span>
                </span>
          </span>
        </div>

        <div class="col-md-12 form-info">
          <span>{{$t('preference.docLink')}}: </span>
          <span>
            <a :href="$t('preference.tankDocLink')" target="_blank">{{$t('preference.tankDocLink')}}</a>
          </span>
        </div>

      </div>
    </div>

    <div class="text-right">
      <button class="btn btn-sm btn-danger mr5"
              @click.stop.prevent="systemCleanup"
              :title="$t('preference.systemCleanupDescription')">
        <i class="fa fa-warning"></i>
        {{$t('preference.systemCleanup')}}
      </button>
      <router-link class="btn btn-sm btn-primary mr5" to="/preference/edit">
        <i class="fa fa-pencil"></i>
        {{$t('edit')}}
      </router-link>
    </div>

  </div>
</template>

<script>
  import NbSwitcher from "../../components/NbSwitcher"

  export default {
    data() {
      return {
        preference: this.$store.state.preference
      }
    },
    methods: {
      systemCleanup() {

        let that = this
        let preference = this.preference

        this.$prompt(that.$t("preference.systemCleanupPrompt"), that.$t("prompt"), {
          inputValue: null,
          confirmButtonText: that.$t("confirm"),
          cancelButtonText: that.$t("cancel"),
          inputPattern: /^.{1,45}$/,
          inputErrorMessage: that.$t("required")
        }).then(({value}) => {

          preference.httpSystemCleanup(value, function () {
            that.$message.success(that.$t("operationSuccess"));
          })
        }).catch(() => {

        });

      }
    },
    components: {
      NbSwitcher
    },
    mounted() {
    }
  }
</script>

<style lang="less" rel="stylesheet/less">
  .backyard-preference {
    .max-height-100 {
      max-height: 100px;
    }

    .preference-block {
      margin-top: 10px;
      margin-bottom: 10px;
    }
  }
</style>
