// src/views/matter/widget/MatterImage.vue
<template>
  <div class="nb-matter-image">

    <div class="tiny-block">
      <div class="p10 mb10 bg-white br5 border" :style="'width:'+previewWidth+'px'" v-show="preview && value">
        <img class="wp100 cursor" :src="value" @click="$photoSwipePlugin.showPhoto(value)"/>
      </div>
    </div>

    <div>
      <div class="input-group">
        <input type="text"
               class="form-control input-sm"
               v-model="value"
               v-if="manual"
               :placeholder="$t('matter.fillInPicLink')">

        <span class="form-control input-sm btn-file text-center pt3 pb0" v-show="!manual">
          <slot name="button">
            <i class="fa fa-cloud-upload"></i>
            <span>{{value?$t('matter.rePick'):$t('matter.chooseImage')}}</span>
          </slot>
          <input ref="refFile" type="file" @change.prevent.stop="triggerUpload"/>
        </span>

        <span class="input-group-btn">
          <button class="btn btn-primary btn-sm mr5" @click.stop.prevent="manual = !manual">
        <i class="fa fa-pencil" v-if="!manual"></i>
        <i class="fa fa-cloud-upload" v-if="manual"></i>
        <span>{{manual?$t('matter.uploadMode'):$t('matter.fillMode')}}</span>
      </button>
          </span>
      </div>

      <div class="italic" v-if="uploadHint">
        {{uploadHint}}
      </div>
    </div>
    <div>
      <UploadMatterPanel :matter="matter"/>
    </div>

  </div>
</template>
<script>
  import Matter from '../../../model/matter/Matter'
  import UploadMatterPanel from "./UploadMatterPanel"
  import {humanFileSize} from "../../../common/filter/str";

  export default {
    data() {
      return {
        manual: false,
        user: this.$store.state.user,
        matter: new Matter()
      }
    },
    components: {
      UploadMatterPanel
    },
    props: {
      preview: {
        //上传的照片是否需要预览
        type: Boolean,
        required: false,
        'default': true
      },
      previewWidth: {
        type: Number,
        required: false,
        'default': 200
      },
      //图片的url.
      value: {
        type: String | null,
        required: true
      },
      //filter.
      filter: {
        type: String,
        required: false,
        "default": "image"
      },
      uploadHint: {
        type: String,
        required: false,
        "default": ""
      }
    },
    methods: {
      del() {
        let that = this
        that.matter.clear()
      },
      triggerUpload() {
        let that = this

        let matter = that.matter;
        matter.puuid = "root"
        matter.uploadHint = that.uploadHint
        matter.filter = that.filter
        matter.privacy = false

        matter.dir = false
        matter.alien = true
        matter.userUuid = that.user.uuid

        let value = that.$refs['refFile'].value
        if (!value) {
          return
        }
        matter.file = that.$refs['refFile'].files[0]


        //判断文件大小。
        if (that.user.sizeLimit >= 0) {
          if (matter.file.size > that.user.sizeLimit) {
            that.$message.error(this.$t('matter.sizeExceedLimit', humanFileSize(matter.file.size), humanFileSize(that.user.sizeLimit)))
            return;
          }
        }


        matter.httpUpload(function () {

          that.$emit("input", matter.getPreviewUrl())

        })


      }
    },
    created() {
    },
    mounted() {

    }
  }

</script>
<style lang="less" rel="stylesheet/less">
  .nb-matter-image {

  }
</style>

// src/pages/matter/widget/MatterImage.tsx
import React from "react";
import TankComponent from "../../../common/component/TankComponent";
import Moon from "../../../common/model/global/Moon";
import Matter from "../../../common/model/matter/Matter";
import ImagePreviewer from "../../widget/previewer/ImagePreviewer";
import { Input, Upload, Button } from "antd";
import UploadMatterPanel from "./UploadMatterPanel";
import "./MatterImage.less";
import MessageBoxUtil from "../../../common/util/MessageBoxUtil";
import SafeUtil from "../../../common/util/SafeUtil";
import Lang from "../../../common/model/global/Lang";

interface IProps {
  value?: string;
  onChange?: (value: string) => any;
  preview?: boolean; //上传的照片是否需要预览
  previewWidth?: number;
  filter?: string;
  uploadHint?: string;
}

interface IState {}

export default class MatterImage extends TankComponent<IProps, IState> {
  // 是否手动上传模式
  manual = false;
  matter = new Matter(this);
  user = Moon.getSingleton().user;

  constructor(props: IProps) {
    super(props);
  }

  changeLink = (e: any) => {
    SafeUtil.safeCallback(this.props.onChange)(e.target.value);
  };

  triggerUpload = (fileObj: any) => {
    const { file } = fileObj;
    const { filter = "image", uploadHint = "" } = this.props;
    if (file) {
      if (this.user.sizeLimit >= 0 && file.size > this.user.sizeLimit) {
        MessageBoxUtil.error(
          Lang.t("matter.sizeExceedLimit", file.size, this.user.sizeLimit)
        );
        return;
      }
      this.matter.assign({
        uploadHint,
        filter,
        file,
        puuid: "root",
        privacy: false,
        dir: false,
        alien: true,
        userUuid: this.user.uuid,
      });
      this.matter.httpUpload(
        () => {
          SafeUtil.safeCallback(this.props.onChange)(
            this.matter.getPreviewUrl()
          );
          this.matter = new Matter();
          this.updateUI();
        },
        () => this.updateUI()
      );
    }
  };

  toggleHandle = () => {
    this.manual = !this.manual;
    this.updateUI();
  };

  render() {
    const { manual, matter } = this;
    const {
      value,
      preview = true,
      previewWidth = 200,
      uploadHint,
    } = this.props;

    return (
      <div className="matter-image">
        <div className="tiny-block">
          {preview && value ? (
            <img
              className="p10 mb10 bg-white br5 border"
              style={{ width: `${previewWidth}px` }}
              src={value}
              onClick={() => ImagePreviewer.showSinglePhoto(value)}
            />
          ) : null}
        </div>
        <div className="composite-box">
          {manual ? (
            <Input
              className="content"
              placeholder={Lang.t("matter.fillInPicLink")}
              value={value}
              onChange={this.changeLink}
            />
          ) : (
            <Upload
              className="content"
              customRequest={this.triggerUpload}
              showUploadList={false}
            >
              <Button className="wp100 border-short">{Lang.t("matter.chooseImage")}</Button>
            </Upload>
          )}
          <Button className="handle" type="primary" onClick={this.toggleHandle}>
            {manual ? Lang.t("matter.uploadMode") : Lang.t("matter.fillMode")}
          </Button>
        </div>
        {uploadHint ? <div className="italic">{uploadHint}</div> : null}
        <UploadMatterPanel matter={matter} />
      </div>
    );
  }
}
