// src/backyard/matter/widget/MatterPanel.vue
<template>
  <div class="widget-matter-panel">

    <div @click.stop.prevent="clickRow">

      <div class="media">

        <div class="pull-left">
          <div class="left-part">
            <span class="basic-span">
            <NbCheckbox v-model="matter.check"/>
            </span>
            <span class="basic-span">
              <img class="matter-icon" :src="matter.getIcon()"/>
            </span>
          </div>
        </div>

        <!--在大屏下的操作栏-->
        <div class="pull-right hidden-sm hidden-xs">
          <div class="right-part" v-if="matter.uuid">

            <span class="matter-operation">

              <i class="fa fa-lock btn-action text-primary" v-if="!matter.dir && matter.privacy" title="设置为公有文件"
                 @click.stop.prevent="matter.httpChangePrivacy(false)"></i>
              <i class="fa fa-unlock btn-action text-primary" v-if="!matter.dir && !matter.privacy" title="设置为私有文件"
                 @click.stop.prevent="matter.httpChangePrivacy(true)"></i>

              <i class="fa fa-info-circle btn-action text-primary" title="文件"
                 @click.stop.prevent="$router.push('/matter/detail/'+matter.uuid)"></i>

              <i class="fa fa-font btn-action text-primary" title="重命名" @click.stop.prevent="prepareRename"></i>
              <i class="fa fa-link btn-action text-primary" title="复制下载链接" v-if="!matter.dir"
                 @click.stop.prevent="clipboard"></i>
              <i class="fa fa-download btn-action text-primary" title="下载"
                 @click.stop.prevent="matter.download()"></i>

              <i class="fa fa-trash btn-action text-danger" title="删除" @click.stop.prevent="deleteMatter"></i>
            </span>
            <span class="matter-size" v-if="matter.dir">
              -
            </span>
            <span class="matter-size" v-else>
              {{matter.size | humanFileSize}}
            </span>

            <span class="matter-date">
              {{matter.updateTime | simpleDateHourMinute}}
            </span>

          </div>
        </div>

        <!--在小屏幕下的操作栏-->
        <div class="pull-right hidden-lg hidden-md">
          <span class="more-btn" @click.stop.prevent="showMore = !showMore">
            <i class="fa fa-ellipsis-h btn-action" title="更多"></i>
          </span>
        </div>

        <div class="media-body">

          <div class="middle-part">

            <span class="matter-name-edit" v-if="matter.editMode">
              <input ref="editInput" class="form-control"
                     :class="matter.uuid"
                     v-model="renameMatterName"
                     placeholder="请输入名称"
                     @blur="blurTrigger()"
                     v-on:keyup.13="enterTrigger()"/>
              </span>
            <span class="matter-name"
                  :title="matter.alien?'该文件是应用数据，存放的系统内头像，logo等文件，或者是通过接口上传的第三方文件':matter.name"
                  :class="{alien:matter.alien}" v-else>
                {{matter.name}} <i class="fa fa-unlock" v-if="!matter.dir && !matter.privacy" title="公有文件，任何人可以访问"></i>
              </span>

          </div>
        </div>
      </div>

    </div>

    <NbExpanding>
      <div class="hidden-lg hidden-md more-panel" v-if="showMore">
        <div class="cell-btn" style="border: none">
          <span>
            {{matter.updateTime | simpleDateHourMinute}}
          </span>

          <span v-if="!matter.dir">
              {{matter.size | humanFileSize}}
          </span>
        </div>

        <div class="cell-btn" v-if="!matter.dir && matter.privacy" title="设置为公有文件"
             @click.stop.prevent="matter.httpChangePrivacy(false)">
          <i class="fa fa-lock"></i>
          设置为公有文件
        </div>

        <div class="cell-btn" v-if="!matter.dir && !matter.privacy" title="设置为私有文件"
             @click.stop.prevent="matter.httpChangePrivacy(true)">
          <i class="fa fa-unlock"></i>
          设置为私有文件
        </div>

        <div class="cell-btn" title="文件详情" @click.stop.prevent="$router.push('/matter/detail/'+matter.uuid)">
          <i class="fa fa-info-circle"></i>
          文件详情
        </div>

        <div class="cell-btn" title="重命名" @click.stop.prevent="prepareRename">
          <i class="fa fa-pencil"></i>
          重命名
        </div>

        <div class="cell-btn" title="复制下载链接" v-if="!matter.dir"
             @click.stop.prevent="clipboard">
          <i class="fa fa-link"></i>
          复制下载链接
        </div>


        <div class="cell-btn" title="下载" v-if="!matter.dir"
             @click.stop.prevent="matter.download()">
          <i class="fa fa-download"></i>
          下载
        </div>

        <div class="cell-btn text-danger" title="删除" @click.stop.prevent="deleteMatter">
          <i class="fa fa-trash"></i>
          删除
        </div>

      </div>
    </NbExpanding>

  </div>

</template>
<script>
  import Matter from '../../../common/model/matter/Matter'
  import NbCheckbox from '../../../common/widget/NbCheckbox'
  import NbExpanding from '../../../common/widget/NbExpanding'
  import $ from 'jquery'
  import Director from './Director'
  import {Message, MessageBox} from 'element-ui'
  import {currentHost, setInputSelection} from '../../../common/util/Utils'

  export default {
    data() {
      return {
        //正在向服务器提交rename的请求
        renamingLoading: false,
        showMore: false,
        //正在重命名的临时字段
        renameMatterName: null
      }
    },
    components: {
      NbExpanding,
      NbCheckbox
    },
    props: {
      matter: {
        type: Matter,
        required: true
      },
      director: {
        type: Director,
        required: true
      }
    },
    watch: {
      'matter.check'(newVal, oldVal) {
        this.$emit('checkMatter', this.matter)
      }
    },
    methods: {
      clickRow() {
        let that = this

        if (this.director.isEditing()) {
          console.error('导演正忙着，不予执行')
          return
        }

        if (this.matter.dir) {
          this.$emit('goToDirectory', that.matter.uuid)
        } else {
          //图片进行预览操作
          if (that.matter.isImage()) {

            this.$emit("previewImage", that.matter)

          } else {
            that.matter.preview()
          }
        }
      },
      deleteMatter() {
        let that = this
        MessageBox.confirm('此操作将永久删除该文件, 是否继续?', '提示', {
          confirmButtonText: '确定',
          cancelButtonText: '取消',
          type: 'warning',
          callback: function (action, instance) {
            if (action === 'confirm') {
              that.matter.httpDelete(function (response) {
                Message.success('删除成功！')
                that.$emit('deleteSuccess', that.matter)
              })
            }

          }
        })
      },
      prepareRename() {
        let that = this

        if (this.director.isEditing()) {
          console.error('导演正忙着，不予执行')
          return
        }
        //告诉导演，自己正在编辑
        this.director.renameMode = true
        this.matter.editMode = true
        this.renameMatterName = this.matter.name

        //稍作延迟，vue的组件才能加载出来
        setTimeout(function () {

          //如果是文件夹，全选中
          let dotIndex = that.matter.name.lastIndexOf('.')
          if (dotIndex === -1) {
            setInputSelection(that.$refs.editInput, 0, that.renameMatterName.length)
          } else {
            setInputSelection(that.$refs.editInput, 0, dotIndex)
          }

        }, 100)

      },
      finishRename() {
        let that = this
        //有可能按enter的时候和blur同时了。
        if (that.renamingLoading) {
          return
        }

        that.renamingLoading = true
        this.matter.httpRename(that.renameMatterName, function () {
          that.renamingLoading = false
          Message.success('重命名成功！')
          //告诉导演，自己编辑完毕
          that.director.renameMode = false
          that.matter.editMode = false

        }, function (errorMessage) {
          that.renamingLoading = false
          Message.error(errorMessage)
          //告诉导演，自己编辑完毕
          that.director.renameMode = false
          that.matter.editMode = false

        })

      },
      finishCreateDirectory() {
        let that = this
        that.matter.name = that.renameMatterName
        that.matter.httpCreateDirectory(function () {
          that.director.createMode = false
          that.editMode = false

          that.matter.render(new Matter())

          that.$emit('createDirectorySuccess', that.matter)

        }, function (errorMessage) {
          that.director.createMode = false
          that.editMode = false
          Message.error(errorMessage)
        })
      },
      blurTrigger() {
        let that = this
        if (that.matter.editMode) {
          if (that.director.createMode) {
            that.finishCreateDirectory()
          } else if (that.director.renameMode) {
            that.finishRename()
          }
        }
      },
      enterTrigger() {
        $(this.$refs.editInput).blur()
      },
      highLight() {
        $(this.$refs.editInput).select()
      },
      clipboard() {

        let textToCopy = this.matter.getDownloadUrl();
        this.$copyPlguin.copy(textToCopy, function () {
          Message.success({
            message: "复制成功!",
            center: true
          })
        })

      }
    },
    created() {
    },
    mounted() {

    }
  }

</script>
<style lang="less" rel="stylesheet/less">

  @import "../../../assets/css/global/variables";

  @base-height: 48px;
  @inner-cell-height: 36px;

  .basic-span {
    display: inline-block;
    vertical-align: middle;
    line-height: @base-height;
    margin-right: 5px;
  }

  .widget-matter-panel {

    border-top: 1px solid #eee;
    background-color: white;

    .media {
      > .pull-left {
        padding-right: 1px;
      }
    }

    .matter-icon {
      width: 24px;
    }

    .left-part {
      margin-left: 10px;
    }

    .middle-part {

      height: @base-height;
      overflow: hidden;

      .matter-name-edit {
        .basic-span;

        width: 90%;

        input {
          width: 100%;
          height: 26px;
          display: inline-block;
          padding: 6px;
        }
      }

      .matter-name {
        .basic-span;
        width: 100%;
        white-space: nowrap;
        text-overflow: ellipsis;
        overflow: hidden;

        &.alien {
          color: @brand-primary;
          font-weight: bold;
        }
      }
    }

    .right-part {

      .matter-operation {
        .basic-span;
        display: none;

        i {
          font-size: 16px;
          margin-right: 5px;

          &:hover {

          }
        }
      }

      .matter-size {
        .basic-span;
        display: inline-block;
        width: 80px;
        text-align: left;
        margin-left: 20px;
      }

      .matter-date {
        .basic-span;
      }
    }

    .more-btn {
      display: inline-block;
      vertical-align: middle;
      line-height: @base-height;
      padding: 0 15px;
    }

    &:hover {
      background-color: aliceblue;
      cursor: pointer;

      .matter-operation {
        display: inline-block;
      }
    }

    .more-panel {
      border-top: 1px solid #eee;
      padding-left: 35px;

      .info {
      }

      .cell-btn {
        border-top: 1px solid #eee;
        line-height: @inner-cell-height;
        vertical-align: middle;
      }
    }
  }

</style>

// src/pages/matter/widget/MatterPanel.tsx
import React from "react";
import copy from "copy-to-clipboard";
import Matter from "../../../common/model/matter/Matter";
import TankComponent from "../../../common/component/TankComponent";
import Director from "./Director";
import "./MatterPanel.less";
import Sun from "../../../common/model/global/Sun";
import StringUtil from "../../../common/util/StringUtil";
import DateUtil from "../../../common/util/DateUtil";
import AnimateUtil from "../../../common/util/AnimateUtil";
import MessageBoxUtil from "../../../common/util/MessageBoxUtil";
import Expanding from "../../widget/Expanding";
import {
  LockFilled,
  UnlockFilled,
  DownloadOutlined,
  ExclamationCircleFilled,
  SmallDashOutlined,
  LinkOutlined,
  DeleteOutlined,
  InfoCircleTwoTone,
  EditOutlined,
  InfoCircleOutlined,
} from "@ant-design/icons";
import { Modal, Checkbox } from "antd";
import { CheckboxChangeEvent } from "antd/es/checkbox";
import SafeUtil from "../../../common/util/SafeUtil";

interface IProps {
  matter: Matter;
  director: Director;
  onCreateDirectoryCallback?: () => any;
  onDeleteSuccess?: () => any;
  onCheckMatter?: (matter?: Matter) => any;
  onPreviewImage?: (matter: Matter) => any;
  onGoToDirectory?: (id: string) => any;
}

interface IState {}

export default class MatterPanel extends TankComponent<IProps, IState> {
  // 正在重命名的临时字段
  renameMatterName: string = "";
  // 正在向服务器提交rename的请求
  renamingLoading: boolean = false;
  // 小屏幕下操作栏
  showMore: boolean = false;

  inputRef = React.createRef<HTMLInputElement>();

  constructor(props: IProps) {
    super(props);
    this.state = {};
  }

  prepareRename = () => {
    const { matter, director } = this.props;
    if (director.isEditing()) {
      console.error("导演正忙着，不予执行");
      return;
    }

    //告诉导演，自己正在编辑
    director.renameMode = true;
    matter.editMode = true;
    this.renameMatterName = matter.name!;
    this.updateUI();
    setTimeout(() => {
      if (!this.inputRef.current) return;
      //如果是文件夹，全选中
      let dotIndex = matter.name!.lastIndexOf(".");
      if (dotIndex === -1) {
        AnimateUtil.setInputSelection(
          this.inputRef.current,
          0,
          this.renameMatterName.length
        );
      } else {
        AnimateUtil.setInputSelection(this.inputRef.current, 0, dotIndex);
      }
    });
  };

  clipboard = () => {
    let textToCopy = this.props.matter.getDownloadUrl();
    copy(textToCopy);
    MessageBoxUtil.success("操作成功");
  };

  deleteMatter = () => {
    Modal.confirm({
      title: "此操作不可撤回, 是否继续?",
      icon: <ExclamationCircleFilled twoToneColor="#FFDC00" />,
      onOk: () => {
        this.props.matter.httpDelete(() => {
          MessageBoxUtil.success("操作成功");
          this.props.onDeleteSuccess!();
        });
      },
    });
  };

  changeMatterName = (e: any) => {
    this.renameMatterName = e.currentTarget.value;
    this.updateUI();
  };

  finishRename = () => {
    //有可能按enter的时候和blur同时了。
    if (this.renamingLoading) {
      return;
    }
    const { matter, director } = this.props;
    this.renamingLoading = true;

    matter.httpRename(
      this.renameMatterName,
      () => {
        this.renamingLoading = false;
        MessageBoxUtil.success("操作成功");
        //告诉导演，自己编辑完毕
        director.renameMode = false;
        matter.editMode = false;
      },
      (msg: string) => {
        this.renamingLoading = false;
        MessageBoxUtil.error(msg);
        //告诉导演，自己编辑完毕
        director.renameMode = false;
        matter.editMode = false;
      },
      () => this.updateUI()
    );
  };

  finishCreateDirectory = () => {
    const { matter, director, onCreateDirectoryCallback } = this.props;
    matter.name = this.renameMatterName;
    matter.httpCreateDirectory(
      () => {
        director.createMode = false;
        matter.editMode = false;
        matter.assign(new Matter());
      },
      (msg: string) => {
        director.createMode = false;
        matter.editMode = false;
        MessageBoxUtil.error(msg);
      },
      () => onCreateDirectoryCallback!()
    );
  };

  blurTrigger = () => {
    const { matter, director } = this.props;
    if (matter.editMode) {
      if (director.createMode) {
        this.finishCreateDirectory();
      } else if (director.renameMode) {
        this.finishRename();
      }
    }
  };

  enterTrigger = (e: any) => {
    if (e.key.toLowerCase() === "enter") {
      this.inputRef.current!.blur();
    }
  };

  changePrivacy = (privacy: boolean) => {
    this.props.matter.httpChangePrivacy(privacy, () => {
      this.updateUI();
    });
  };

  checkToggle = (e: CheckboxChangeEvent) => {
    this.props.matter.check = e.target.checked;
    this.props.onCheckMatter!(this.props.matter);
  };

  highLight = () => {
    this.inputRef.current!.select();
  };

  clickRow = () => {
    const { matter, director, onGoToDirectory, onPreviewImage } = this.props;
    if (director.isEditing()) {
      console.error("导演正忙着，不予执行");
      return;
    }

    if (matter.dir) {
      onGoToDirectory!(matter.uuid!);
    } else {
      //图片进行预览操作
      if (matter.isImage()) {
        onPreviewImage!(matter);
      } else {
        matter.preview();
      }
    }
  };

  toggleHandles = () => {
    this.showMore = !this.showMore;
    this.updateUI();
  };

  render() {
    const { matter } = this.props;

    return (
      <div className="widget-matter-panel">
        <div onClick={(e) => SafeUtil.stopPropagationWrap(e)(this.clickRow())}>
          <div className="media clearfix">
            <div className="pull-left">
              <div className="left-part">
                <span className="basic-span basic-span-hot">
                  <Checkbox
                    onClick={(e) => SafeUtil.stopPropagationWrap(e)}
                    checked={matter.check}
                    onChange={this.checkToggle}
                  />
                </span>
                <span className="basic-span">
                  <img className="matter-icon" src={matter.getIcon()} />
                </span>
              </div>
            </div>

            {/*在大屏幕下的操作栏*/}
            <div className="pull-right visible-pc">
              {matter.uuid && (
                <div className="right-part">
                  <span className="matter-operation">
                    {!matter.dir && matter.privacy && (
                      <UnlockFilled
                        className="btn-action blue"
                        onClick={(e) =>
                          SafeUtil.stopPropagationWrap(e)(
                            this.changePrivacy(false)
                          )
                        }
                      />
                    )}
                    {!matter.dir && !matter.privacy && (
                      <LockFilled
                        className="btn-action blue"
                        onClick={(e) =>
                          SafeUtil.stopPropagationWrap(e)(
                            this.changePrivacy(true)
                          )
                        }
                      />
                    )}
                    <InfoCircleTwoTone
                      className="btn-action blue"
                      onClick={(e) =>
                        SafeUtil.stopPropagationWrap(e)(
                          Sun.navigateTo("/matter/detail/" + matter.uuid)
                        )
                      }
                    />
                    <EditOutlined
                      className="btn-action blue"
                      onClick={(e) =>
                        SafeUtil.stopPropagationWrap(e)(this.prepareRename())
                      }
                    />
                    <LinkOutlined
                      className="btn-action blue"
                      onClick={(e) =>
                        SafeUtil.stopPropagationWrap(e)(this.clipboard())
                      }
                    />
                    <DownloadOutlined
                      className="btn-action blue"
                      onClick={(e) =>
                        SafeUtil.stopPropagationWrap(e)(matter.download())
                      }
                    />
                    <DeleteOutlined
                      className="btn-action red"
                      onClick={(e) =>
                        SafeUtil.stopPropagationWrap(e)(this.deleteMatter())
                      }
                    />
                  </span>
                  <span className="matter-size">
                    {StringUtil.humanFileSize(matter.size)}
                  </span>
                  <span className="matter-date">
                    {DateUtil.simpleDateHourMinute(matter.updateTime)}
                  </span>
                </div>
              )}
            </div>

            <div className="pull-right visible-mobile">
              <span
                className="more-btn"
                onClick={(e) =>
                  SafeUtil.stopPropagationWrap(e)(this.toggleHandles())
                }
              >
                <SmallDashOutlined className="btn-action navy f18" />
              </span>
            </div>

            <div className="media-body">
              <div className="middle-part">
                {matter.editMode ? (
                  <span className="matter-name-edit">
                    <input
                      ref={this.inputRef}
                      className={matter.uuid!}
                      value={this.renameMatterName}
                      onChange={this.changeMatterName.bind(this)}
                      placeholder="请输入名称"
                      onBlur={this.blurTrigger.bind(this)}
                      onKeyUp={this.enterTrigger.bind(this)}
                    />
                  </span>
                ) : (
                  <span className="matter-name">
                    {matter.name}
                    {!matter.dir && !matter.privacy && (
                      <UnlockFilled className="icon" />
                    )}
                  </span>
                )}
              </div>
            </div>
          </div>
        </div>

        <Expanding>
          {this.showMore ? (
            <div className="more-panel">
              <div className="cell-btn navy text">
                <span>{DateUtil.simpleDateHourMinute(matter.updateTime)}</span>
                <span className="matter-size">
                  {StringUtil.humanFileSize(matter.size)}
                </span>
              </div>

              {!matter.dir && matter.privacy && (
                <div
                  className="cell-btn navy"
                  onClick={(e) =>
                    SafeUtil.stopPropagationWrap(e)(this.changePrivacy(false))
                  }
                >
                  <UnlockFilled className="btn-action mr5" />
                  设置为公有文件
                </div>
              )}

              {!matter.dir && !matter.privacy && (
                <div
                  className="cell-btn navy"
                  onClick={(e) =>
                    SafeUtil.stopPropagationWrap(e)(this.changePrivacy(true))
                  }
                >
                  <LockFilled className="btn-action mr5" />
                  设置为私有文件
                </div>
              )}

              <div
                className="cell-btn navy"
                onClick={(e) =>
                  SafeUtil.stopPropagationWrap(e)(
                    Sun.navigateTo("/matter/detail/" + matter.uuid)
                  )
                }
              >
                <InfoCircleOutlined className="btn-action mr5" />
                文件详情
              </div>
              <div
                className="cell-btn navy"
                onClick={(e) =>
                  SafeUtil.stopPropagationWrap(e)(this.prepareRename())
                }
              >
                <EditOutlined className="btn-action mr5" />
                重命名
              </div>
              <div
                className="cell-btn navy"
                onClick={(e) =>
                  SafeUtil.stopPropagationWrap(e)(this.clipboard())
                }
              >
                <LinkOutlined className="btn-action mr5" />
                复制下载链接
              </div>
              <div
                className="cell-btn navy"
                onClick={(e) =>
                  SafeUtil.stopPropagationWrap(e)(matter.download())
                }
              >
                <DownloadOutlined className="btn-action mr5" />
                下载
              </div>
              <div
                className="cell-btn red"
                onClick={(e) =>
                  SafeUtil.stopPropagationWrap(e)(this.deleteMatter())
                }
              >
                <DeleteOutlined className="btn-action mr5" />
                删除
              </div>
            </div>
          ) : null}
        </Expanding>
      </div>
    );
  }
}
