// src/views/preference/Edit.vue
<template>
  <div class="backyard-preference-edit animated fadeIn">

    <div class="tank-box bg-white br4 p20 mt10">
      <div class="row" v-validator="preference.validatorSchema.name.error">
        <label class="col-md-2 control-label mt5 compulsory">
          {{$t('preference.websiteName')}}
        </label>
        <div class="col-md-10 validate">
          <input type="text" class="form-control" v-model="preference.name">
        </div>
      </div>

      <div class="row mt10">
        <label class="col-md-2 control-label mt5">
          {{$t('preference.logo')}}
        </label>
        <div class="col-md-10">
          <MatterImage v-model="preference.logoUrl" :uploadHint="$t('preference.logoSquare')"/>
        </div>
      </div>

      <div class="row mt10">
        <label class="col-md-2 control-label mt5">favicon</label>
        <div class="col-md-10">
          <MatterImage v-model="preference.faviconUrl" filter=".ico"
                       :uploadHint="$t('preference.onlyAllowIco')"
                       :previewWidth="60"/>
        </div>
      </div>

      <div class="row mt10">
        <label class="col-md-2 control-label mt5">{{$t('preference.copyright')}}</label>
        <div class="col-md-10">
          <input type="text" class="form-control" v-model="preference.copyright">
        </div>
      </div>

      <div class="row mt10">
        <label class="col-md-2 control-label mt5">{{$t('preference.extraInfo')}}</label>
        <div class="col-md-10">
          <input type="text" class="form-control" v-model="preference.record">
        </div>
      </div>


      <div class="row mt10">
        <label class="col-md-2 control-label mt5">{{$t('preference.officeUrl')}}</label>
        <div class="col-md-10">
          <input type="text" class="form-control" v-model="preference.officeUrl">
        </div>
      </div>


      <div class="row mt10">
        <label class="col-md-2 control-label mt5">{{$t('preference.zipMaxNumLimit')}}</label>
        <div class="col-md-10">
          <input type="text" class="form-control" v-model="preference.downloadDirMaxNum">
        </div>
      </div>


      <div class="row mt10">
        <label class="col-md-2 control-label mt5">{{$t('preference.zipMaxSizeLimit')}} </label>
        <div class="col-md-10">
          <div class="row">
            <div class="col-xs-6">
              <input type="number" class="form-control" v-model="preference.downloadDirMaxSize">
            </div>
            <div class="col-xs-6" style="line-height:30px;">
              {{$t('preference.current')}}:
              <span v-if="preference.downloadDirMaxSize < 0">{{$t('preference.noLimit')}}</span>
              <span v-else>{{preference.downloadDirMaxSize | humanFileSize}}</span>
            </div>
          </div>

        </div>

      </div>

      <div class="row mt10">
        <label class="col-md-2 control-label mt5">{{$t('preference.userDefaultSizeLimit')}}</label>
        <div class="col-md-10">
          <div class="row">
            <div class="col-xs-6">
              <input type="number" class="form-control" v-model="preference.defaultTotalSizeLimit">
            </div>
            <div class="col-xs-6" style="line-height:30px;">
              {{$t('preference.current')}}:
              <span v-if="preference.defaultTotalSizeLimit < 0">{{$t('preference.noLimit')}}</span>
              <span v-else>{{preference.defaultTotalSizeLimit | humanFileSize}}</span>
            </div>
          </div>

        </div>

      </div>

      <div class="row mt10">
        <label class="col-md-2 control-label mt5">{{$t('preference.allowRegister')}}</label>
        <div class="col-md-10">
          <NbSwitcher v-model="preference.allowRegister"/>
        </div>
      </div>

    </div>

    <div class="row mt10">
      <div class="col-md-12">
        <div>
          <CreateSaveButton :entity="preference" :callback="save"/>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import CreateSaveButton from '../../components/CreateSaveButton'
  import MatterImage from '../matter/widget/MatterImage'
  import Preference from '../../model/preference/Preference'
  import NbSwitcher from "../../components/NbSwitcher"

  export default {
    name: 'edit',
    data() {
      return {
        globalPreference: this.$store.state.preference,
        preference: new Preference()
      }
    },
    components: {
      MatterImage,
      CreateSaveButton,
      NbSwitcher
    },
    methods: {
      save() {
        let that = this;
        this.preference.httpSave(function (response) {

          that.$message.success({
            message: that.$t('operationSuccess')
          });

          that.globalPreference.render(response.data.data);

          that.preference.updateTitleAndFavicon();

          that.$router.go(-1);
        })
      }
    },
    mounted() {
      let that = this;
      //为了让按钮的文字显示为“保存”
      this.preference.editMode = true
      this.preference.httpFetch()
    }
  }
</script>

<style lang="less" rel="stylesheet/less">

</style>

// src/pages/preference/Edit.tsx
import React from "react";
import { RouteComponentProps } from "react-router-dom";
import "./Edit.less";
import TankComponent from "../../common/component/TankComponent";
import User from "../../common/model/user/User";
import Moon from "../../common/model/global/Moon";
import TankTitle from "../widget/TankTitle";
import { Button, Form, Input, InputNumber, Switch } from "antd";
import { SaveOutlined } from "@ant-design/icons";
import TankContentCard from "../widget/TankContentCard";
import Preference from "../../common/model/preference/Preference";
import FileUtil from "../../common/util/FileUtil";
import { FormInstance } from "antd/lib/form";
import MessageBoxUtil from "../../common/util/MessageBoxUtil";
import Sun from "../../common/model/global/Sun";
import Lang from "../../common/model/global/Lang";
import MatterImage from "../matter/widget/MatterImage";

interface IProps extends RouteComponentProps {}

interface IState {}

export default class Edit extends TankComponent<IProps, IState> {
  formRef = React.createRef<FormInstance>();

  user: User = Moon.getSingleton().user;
  preference: Preference = Moon.getSingleton().preference;

  constructor(props: IProps) {
    super(props);

    this.state = {};

    this.preference.detailLoading = true;
  }

  componentDidMount() {
    let that = this;

    that.refreshPreference();
  }

  refreshPreference() {
    let that = this;

    that.preference.httpFetch(function () {
      that.preference.detailLoading = false;
      that.updateUI();
    });
  }

  onFinish(values: any) {
    console.log("Success:", values);

    let that = this;

    let user = that.user;

    that.preference.assign(values);

    that.preference.httpSave(function () {
      MessageBoxUtil.success(Lang.t("operationSuccess"));

      Sun.updateFrame();

      Sun.navigateTo("/preference/index");
    });
  }

  onFinishFailed(errorInfo: any) {
    console.log("Failed:", errorInfo);
  }

  render() {
    let that = this;

    let preference = that.preference;

    const layout = {
      labelCol: { span: 6 },
      wrapperCol: { span: 18 },
    };

    let initialValues: any = preference.getForm();

    return (
      <div className="page-preference-edit">
        <TankTitle name={Lang.t("preference.editPreference")}></TankTitle>

        <TankContentCard loading={preference.detailLoading}>
          <Form
            {...layout}
            name="basic"
            ref={this.formRef}
            initialValues={initialValues}
            onFinish={this.onFinish.bind(this)}
            onFinishFailed={this.onFinishFailed.bind(this)}
            onValuesChange={() => that.updateUI()}
          >
            <Form.Item
              label={Lang.t("preference.websiteName")}
              name="name"
              rules={[
                {
                  required: true,
                  message: Lang.t("preference.enterWebsiteName"),
                },
              ]}
            >
              <Input />
            </Form.Item>

            <Form.Item label="logo" name="logoUrl">
              <MatterImage uploadHint={Lang.t("preference.logoSquare")} />
            </Form.Item>

            <Form.Item label="favicon" name="faviconUrl">
              <MatterImage
                filter=".ico"
                previewWidth={60}
                uploadHint={Lang.t("preference.onlyAllowIco")}
              />
            </Form.Item>

            <Form.Item label={Lang.t("preference.copyright")} name="copyright">
              <Input />
            </Form.Item>

            <Form.Item label={Lang.t("preference.extraInfo")} name="record">
              <Input />
            </Form.Item>

            <Form.Item label={Lang.t("preference.officeUrl")} name="officeUrl">
              <Input />
            </Form.Item>

            <Form.Item
              label={Lang.t("preference.zipMaxNumLimit")}
              name="downloadDirMaxNum"
              rules={[
                {
                  required: true,
                  message: Lang.t("preference.enterZipMaxNumLimit"),
                },
              ]}
            >
              <InputNumber min={-1} max={1000} className="w150" />
            </Form.Item>

            <Form.Item
              label={Lang.t("preference.zipMaxSizeLimit")}
              required={true}
            >
              <Form.Item
                name="downloadDirMaxSize"
                rules={[
                  {
                    required: true,
                    message: Lang.t("preference.enterZipMaxSizeLimit"),
                  },
                ]}
                noStyle
              >
                <InputNumber min={-1} className="w150" />
              </Form.Item>
              <span className="pl10">
                {" "}
                {Lang.t("preference.current")}:
                {this.formRef && this.formRef.current
                  ? FileUtil.humanFileSize(
                      this.formRef.current.getFieldValue("downloadDirMaxSize")
                    )
                  : FileUtil.humanFileSize(preference.defaultTotalSizeLimit)}
              </span>
            </Form.Item>

            <Form.Item
              label={Lang.t("preference.userDefaultSizeLimit")}
              required={true}
            >
              <Form.Item
                name="defaultTotalSizeLimit"
                rules={[
                  {
                    required: true,
                    message: Lang.t("preference.enterUserDefaultSizeLimit"),
                  },
                ]}
                noStyle
              >
                <InputNumber min={-1} className="w150" />
              </Form.Item>
              <span className="pl10">
                {" "}
                {Lang.t("preference.current")}:
                {this.formRef && this.formRef.current
                  ? FileUtil.humanFileSize(
                      this.formRef.current.getFieldValue(
                        "defaultTotalSizeLimit"
                      )
                    )
                  : FileUtil.humanFileSize(preference.defaultTotalSizeLimit)}
              </span>
            </Form.Item>

            <Form.Item
              label={Lang.t("preference.allowRegister")}
              name="allowRegister"
              required={true}
              valuePropName="checked"
            >
              <Switch />
            </Form.Item>

            <div className="text-right">
              <Button type="primary" htmlType="submit" icon={<SaveOutlined />}>
                {Lang.t("save")}
              </Button>
            </div>
          </Form>
        </TankContentCard>
      </div>
    );
  }
}
