// src/pages/user/Detail.tsx
import React from 'react';
import "./Detail.less"
import TankComponent from "../../common/component/TankComponent";
import {Button, Tag} from 'antd';
import InfoCell from "../widget/InfoCell";
import User from "../../common/model/user/User";
import Moon from "../../common/model/global/Moon";
import DateUtil from "../../common/util/DateUtil";
import TankTitle from '../widget/TankTitle';
import TankContentCard from "../widget/TankContentCard";
import {Link, RouteComponentProps} from "react-router-dom";
import ImagePreviewer from "../widget/previewer/ImagePreviewer";
import {UserRole, UserRoleMap} from "../../common/model/user/UserRole";
import FileUtil from "../../common/util/FileUtil";
import {UserStatus, UserStatusMap} from "../../common/model/user/UserStatus";
import BrowserUtil from "../../common/util/BrowserUtil";
import SingleTextModal from "../widget/SingleTextModal";
import MessageBoxUtil from "../../common/util/MessageBoxUtil";
import ChangePasswordModal from "./widget/ChangePasswordModal";
import {EditOutlined, UnlockOutlined, UserSwitchOutlined} from '@ant-design/icons';
import TransfigurationModal from "./widget/TransfigurationModal";
import {StopOutlined} from "@ant-design/icons/lib";
import Lang from "../../common/model/global/Lang";

interface RouteParam {
  uuid: string
}


interface IProps extends RouteComponentProps<RouteParam> {

}

interface IState {

}

export default class Detail extends TankComponent <IProps, IState> {

  //登录的那个用户
  user: User = Moon.getSingleton().user

  //当前页面正在编辑的用户
  currentUser: User = new User(this)

  constructor(props: IProps) {
    super(props)
    this.state = {}
  }


  componentDidMount() {
    let that = this
    let match = this.props.match;
    this.currentUser.uuid = match.params.uuid;
    this.currentUser.httpDetail()
  }

  resetPassword() {
    let that = this

    SingleTextModal.open(Lang.t("user.enterNewPassword"), "", function (text: string) {
      that.currentUser.httpResetPassword(text, function (response: any) {
        MessageBoxUtil.success(Lang.t("operationSuccess"))
      })
    })

  }

  transfiguration() {

    let user: User = this.user
    let currentUser: User = this.currentUser
    TransfigurationModal.open(currentUser)

  }

  toggleStatus() {
    let that = this
    let user: User = this.user
    let currentUser: User = this.currentUser
    currentUser.httpToggleStatus(function () {
      MessageBoxUtil.success(Lang.t("operationSuccess"))
      that.updateUI()
    })
  }

  changePassword() {

    let user: User = this.user
    let currentUser: User = this.currentUser
    ChangePasswordModal.open(currentUser, function () {
      MessageBoxUtil.success(Lang.t("operationSuccess"))
    })
  }

  render() {

    let user: User = this.user
    let currentUser: User = this.currentUser

    return (

      <div className="page-user-detail">

        <TankTitle name={Lang.t("user.profile")}>

          {
            user.role === UserRole.ADMINISTRATOR && (
              <Button className='ml10' type="primary"
                      icon={<UnlockOutlined/>}
                      onClick={this.resetPassword.bind(this)}>
                {Lang.t("user.resetPassword")}
              </Button>
            )
          }

          {
            user.role === UserRole.ADMINISTRATOR && (
              <Button className='ml10' type="primary"
                      icon={<UserSwitchOutlined/>}
                      onClick={this.transfiguration.bind(this)}>
                {Lang.t("user.transfiguration")}
              </Button>
            )
          }

          {
            currentUser.uuid === user.uuid && (
              <Button className='ml10' type="primary" onClick={this.changePassword.bind(this)} icon={<UnlockOutlined/>}>
                {Lang.t("user.changePassword")}
              </Button>
            )
          }

          <Link to={'/user/edit/' + currentUser.uuid}>
            <Button className='ml10' type="primary" icon={<EditOutlined/>}>
              {Lang.t("edit")}
            </Button>
          </Link>

          {
            (user.role === UserRole.ADMINISTRATOR && currentUser.uuid !== user.uuid) && (
              <Button className='ml10' type="primary"
                      danger={currentUser.status === UserStatus.OK}
                      icon={<StopOutlined/>}
                      onClick={this.toggleStatus.bind(this)}>
                {currentUser.status === UserStatus.OK ? Lang.t("user.disable") : Lang.t("user.active")}
              </Button>
            )
          }

        </TankTitle>

        <TankContentCard loading={currentUser.detailLoading}>

          <div className="text-center mv20">
            <img className="avatar-large" alt="avatar" src={currentUser.getAvatarUrl()} onClick={() => {
              ImagePreviewer.showSinglePhoto(currentUser.getAvatarUrl(true))
            }}/>
            <div className="f24">
              {currentUser.username}
            </div>
          </div>


          <InfoCell name={Lang.t("user.role")}>
            <Tag color={UserRoleMap[currentUser.role].color}>{UserRoleMap[currentUser.role].name}</Tag>
          </InfoCell>


          <InfoCell name={Lang.t("user.singleFileSizeLimit")}>
            {FileUtil.humanFileSize(currentUser.sizeLimit)}
          </InfoCell>


          <InfoCell name={Lang.t("user.totalFileSizeLimit")}>
            {FileUtil.humanFileSize(currentUser.totalSizeLimit)}
          </InfoCell>


          <InfoCell name={Lang.t("user.totalFileSize")}>
            {FileUtil.humanFileSize(currentUser.totalSize)}
          </InfoCell>


          <InfoCell name={Lang.t("user.status")}>
            <Tag color={UserStatusMap[currentUser.status].color}>{UserStatusMap[currentUser.status].name}</Tag>
          </InfoCell>


          <InfoCell name={Lang.t("user.lastLoginIp")}>
            {currentUser.lastIp}
          </InfoCell>


          <InfoCell name={Lang.t("user.lastLoginTime")}>
            {DateUtil.simpleDateTime(currentUser.lastTime)}
          </InfoCell>

          <InfoCell name={Lang.t("user.webdavLink")}>
            {BrowserUtil.fullHost() + "/api/dav"}
          </InfoCell>

          {
            currentUser.role === UserRole.ADMINISTRATOR && (
              <InfoCell name={Lang.t("user.docLink")}>
                <a className="f14" href="https://tank-doc.eyeblue.cn" target="_blank">
                  https://tank-doc.eyeblue.cn
                </a>
              </InfoCell>
            )
          }

        </TankContentCard>


      </div>
    )
  }
}

// src/views/user/Detail.vue
<template>
  <div class="backyard-user-detail animated fadeIn ">

    <div class="user-block tank-box">
      <div class="media">

        <div class="mr20" :class="{'pull-left':!$store.state.config.mobile}">
          <img class="img-container cursor img-circle"
               :class="{'img-blg':!$store.state.config.mobile,'img-lg':$store.state.config.mobile}"
               @click="$photoSwipePlugin.showPhoto(currentUser.getAvatarUrl())"
               :src="currentUser.getAvatarUrl()">
        </div>

        <div class="media-body">
          <div class="cell-title">
            <h1 class="mt10">{{currentUser.username}}</h1>
          </div>
          <div>
            <div class="row">

              <div class="col-md-12 form-info">
                <span>{{$t('user.role')}}:</span>
                <span>
                      {{$t(UserRoleMap[currentUser.role].name)}}
                    </span>
              </div>

              <div class="col-md-12 form-info">
                <span>{{$t('user.singleFileSizeLimit')}}:</span>
                <span v-if="currentUser.sizeLimit >= 0">
                            {{currentUser.sizeLimit | humanFileSize}}
                          </span>
                <span v-else>
                            {{$t('user.noLimit')}}
                          </span>
              </div>
              <div class="col-md-12 form-info">
                <span>{{$t('user.totalFileSizeLimit')}}:</span>
                <span v-if="currentUser.totalSizeLimit >= 0">
                            {{currentUser.totalSizeLimit | humanFileSize}}
                          </span>
                <span v-else>
                  {{$t('user.noLimit')}}
                </span>
              </div>

              <div class="col-md-12 form-info">
                <span>{{$t('user.totalFileSize')}}:</span>
                <span>
                 {{currentUser.totalSize | humanFileSize}}
                </span>
              </div>

              <div class="col-md-12 form-info">
                <span>{{$t('user.status')}}:</span>

                <span :class="'text-'+UserStatusMap[currentUser.status].style">
                  {{$t(UserStatusMap[currentUser.status].name)}}
                </span>
              </div>

              <div class="col-md-12 form-info">
                <span>{{$t('user.lastLoginIp')}}:</span>
                <span>
                     {{currentUser.lastIp}}
                    </span>
              </div>


              <div class="col-md-12 form-info">
                <span>{{$t('user.lastLoginTime')}}:</span>
                <span>
                     {{currentUser.lastTime | simpleDateTime}}
                    </span>
              </div>

              <div class="col-md-12 form-info">
                <span>{{$t('user.webdavLink')}}:</span>
                <span>
                  {{webdavLink}}
                </span>
              </div>

              <div class="col-md-12 form-info" v-if="user.role === UserRole.ADMINISTRATOR">
                <span>{{$t('user.docLink')}}:</span>
                <a class="f14" href="https://tank-doc.eyeblue.cn">
                  https://tank-doc.eyeblue.cn
                </a>
              </div>

            </div>


          </div>
        </div>

      </div>
    </div>


    <div class="text-right" v-if="user.username!=='demo'">
      <button class="btn btn-sm btn-primary mb5 mr10" v-if="user.role === UserRole.ADMINISTRATOR"
              @click.stop.prevent="resetPassword">
        <i class="fa fa-lock"></i>
        {{$t('user.resetPassword')}}
      </button>
      <button class="btn btn-sm btn-primary mb5 mr10" v-if="user.role === UserRole.ADMINISTRATOR"
              @click.stop.prevent="currentUser.transfiguration()">
        <i class="fa fa-user-secret"></i>
        {{$t('user.transfiguration')}}
      </button>
      <button class="btn btn-sm btn-primary mb5 mr10" v-if="currentUser.uuid === user.uuid"
              @click.stop.prevent="changePassword">
        <i class="fa fa-lock"></i>
        {{$t('user.changePassword')}}
      </button>
      <button class="btn btn-sm btn-primary mb5"
              @click.stop.prevent="$router.push('/user/edit/' + currentUser.uuid)">
        <i class="fa fa-pencil"></i>
        {{$t('edit')}}
      </button>
    </div>


  </div>
</template>

<script>
  import NbExpanding from '../../components/NbExpanding.vue'
  import User from '../../model/user/User'
  import {MessageBox} from 'element-ui'
  import {UserRole, UserRoleList, UserRoleMap} from "../../model/user/UserRole";
  import {UserStatus, UserStatusList, UserStatusMap} from "../../model/user/UserStatus";
  import {handleImageUrl} from "../../common/util/ImageUtil";
  import {currentHost} from "../../common/util/Utils";

  export default {
    data() {
      return {
        UserRole,
        UserRoleList,
        UserRoleMap,
        UserStatus,
        UserStatusList,
        UserStatusMap,
        user: this.$store.state.user,
        currentUser: new User(),
        breadcrumbs: this.$store.state.breadcrumbs
      }
    },
    components: {
      NbExpanding
    },
    computed: {
      "webdavLink"() {
        return currentHost() + "/api/dav"
      }
    },
    methods: {
      handleImageUrl,
      currentUserUpdate(uuid) {
        if (uuid) {
          this.currentUser.uuid = uuid
          this.currentUser.httpDetail()
        } else {
          this.currentUser.uuid = this.user.uuid
          this.currentUser.httpDetail()
        }
      },
      changePassword() {
        this.$router.push('/user/change/password')
      },
      resetPassword() {
        let that = this
        MessageBox.prompt(that.$t('user.enterPassword'), that.$t('prompt'), {
          confirmButtonText: that.$t("confirm"),
          cancelButtonText: that.$t("cancel"),
          inputPattern: /.+/,
          inputErrorMessage: that.$t('user.cannotBeNull')
        }).then(({value}) => {
          that.currentUser.httpUserResetPassword(value, function (response) {
            that.$message.success({
              message: that.$t('operationSuccess')
            })
          })
        }).catch(() => {
        })
      }
    },
    watch: {
      '$store.state.route.params.uuid'(newVal, oldVal) {
        this.currentUserUpdate(newVal)
      }
    },
    created() {
      let that = this
      if (this.user.role !== UserRole.ADMINISTRATOR) {
        this.breadcrumbs.splice(0, this.breadcrumbs.length)
        this.breadcrumbs.push({
          displayDirect: true,
          title: that.$t('user.profile')
        })
      }
    },
    mounted() {
      this.currentUserUpdate(this.$store.state.route.params.uuid)

    }
  }

</script>
<style lang="less" rel="stylesheet/less">
  .backyard-user-detail {

    .user-block {
      margin-top: 10px;
      margin-bottom: 10px;
    }

  }
</style>
