// src/pages/matter/widget/UploadMatterPanel.tsx
import React from "react";
import TankComponent from "../../../common/component/TankComponent";
import Matter from "../../../common/model/matter/Matter";
import StringUtil from "../../../common/util/StringUtil";
import { Progress } from "antd";
import "./UploadMatterPanel.less";

interface IProps {
  matter: Matter;
}

interface IState {}

export default class UploadMatterPanel extends TankComponent<IProps, IState> {
  constructor(props: IProps) {
    super(props);
    this.state = {};
  }

  format = (percent: number) => {
    return `${percent.toFixed(1)}%`
  };

  render() {
    const { matter } = this.props;
    return (
      <div className="upload-matter-panel">
        {matter.loading ? (
          <div className="huge-block clearfix">
            <div className="media">
              <div className="media-body">{matter.file!.name}</div>
            </div>
            <Progress
              className="progress"
              strokeColor={{
                from: "#108ee9",
                to: "#87d068",
              }}
              format={() => this.format(matter.progress * 100)}
              percent={matter.progress * 100}
              status="active"
            />
            <div>
              {`已上传: ${StringUtil.humanFileSize(
                matter.file!.size * matter.progress
              )}/${StringUtil.humanFileSize(
                matter.file!.size
              )} 速度:${StringUtil.humanFileSize(matter.speed)}s`}
            </div>
          </div>
        ) : null}
      </div>
    );
  }
}

// src/backyard/matter/widget/UploadMatterPanel.vue
<template>
  <div class="upload-matter-panel">
    <NbExpanding>
      <div class="huge-block clearfix"
           v-if="matter.loading">
        <div class="media">
          <div class="pull-right">
            <i class="btn-action f16 fa fa-trash text-danger" v-if="false" @click.stop.prevent="del()"></i>
          </div>
          <div class="media-body">{{matter.file.name}}</div>
        </div>
        <div class="progress" :class="{'progress-striped active' : matter.loading}">
          <div :style="'width: '+(matter.progress*100)+'%'" class="progress-bar progress-bar-primary">
            <span>已上传 {{(matter.progress * 100).toFixed(1)}}%</span>
          </div>
        </div>
        <div>
          已上传:{{ (matter.file.size * matter.progress).toFixed(0) | humanFileSize }}/{{ matter.file.size |
          humanFileSize}}
          速度:{{matter.speed | humanFileSize}}/s

        </div>
      </div>
    </NbExpanding>

  </div>
</template>
<script>
  import Matter from '../../../common/model/matter/Matter'
  import NbExpanding from "../../../common/widget/NbExpanding"


  export default {
    data() {
      return {}
    },
    components: {

      NbExpanding
    },
    props: {
      matter: {
        type: Matter,
        required: true
      }
    },
    methods: {
      del() {
        let that = this
        that.matter.clear()
      }
    },
    created() {
    },
    mounted() {

    }
  }

</script>
<style lang="less" rel="stylesheet/less">
  .upload-matter-panel {

    .huge-block {
      background-color: white;
      border-radius: 5px;
      padding: 10px;
      border: 1px solid #eeeeee;
      margin-bottom: 10px;

      .progress {
        margin-bottom: 10px;
      }

      .media {
        margin-bottom: 5px;
        .media-body {
          cursor: pointer;
          color: #555;
          font-size: 15px;
          font-weight: bold;
          white-space: nowrap;
          text-overflow: ellipsis;
        }
      }

    }

  }
</style>
