// src/backyard/dashboard/widget/RatePanel.vue
<template>
  <span class="widget-rate-panel">
    <span class="name">{{name}}</span>

    <span class="infinite" v-if="infinite">∞</span>
    <span class="no-data" v-else-if="noData"> - </span>
    <span v-else>{{value>0?'+':''}}{{value}}%</span>

    <i class="fa fa-arrow-down text-success" v-if="!noData && value<0"></i>
    <i class="fa fa-arrow-up text-danger" v-if="!noData && (infinite || value>=0)"></i>
  </span>
</template>

<script>

  export default {
    data: function () {
      return {}
    },
    computed: {
      noData() {
        return this.standardValue === 0 && this.compareValue === 0
      },
      infinite() {
        return this.standardValue === 0 && this.compareValue > 0
      },
      value() {
        if (this.standardValue === 0) {
          if (this.compareValue === 0) {
            return 0;
          } else {
            return 100;
          }
        } else {
          let v1 = this.compareValue - this.standardValue
          let v2 = v1 / this.standardValue
          return (v2 * 100).toFixed(0)
        }
      }
    },
    props: {
      name: {
        type: String,
        required: false,
        'default': ""
      },
      standardValue: {
        type: Number,
        required: true,
        'default': 0
      },
      compareValue: {
        type: Number,
        required: true,
        'default': 0
      }
    },
    components: {},
    methods: {},
    mounted() {
      let that = this;
    }
  }

</script>

<style lang="less" rel="stylesheet/less">
  @import "../../../assets/css/global/variables";

  .widget-rate-panel {
    margin-right: 5px;
    .infinite {

    }
    .no-data {
    }

  }
</style>

// src/pages/dashboard/widget/RatePanel.tsx
import React from 'react';
import "./RatePanel.less"
import TankComponent from "../../../common/component/TankComponent";
import {ArrowDownOutlined, ArrowUpOutlined} from "@ant-design/icons/lib";
import Color from "../../../common/model/base/option/Color";

interface IProps {
  name: string
  standardValue: number
  compareValue: number
}

interface IState {

}

export default class RatePanel extends TankComponent <IProps, IState> {

  constructor(props: IProps) {
    super(props)
    this.state = {}
  }


  componentDidMount() {

  }

  getValue(): number {
    if (this.props.standardValue === 0) {
      if (this.props.compareValue === 0) {
        return 0;
      } else {
        return 100;
      }
    } else {
      let v1 = this.props.compareValue - this.props.standardValue
      let v2 = v1 / this.props.standardValue
      return parseInt((v2 * 100).toFixed(0))
    }
  }

  render() {

    let that = this
    let name: string = this.props.name

    let noData: boolean = this.props.standardValue === 0 && this.props.compareValue === 0
    let infinite: boolean = this.props.standardValue === 0 && this.props.compareValue > 0
    let value: number = this.getValue()

    return (
      <span className="widget-rate-panel">

            <span className="name">{name}</span>

        {infinite ? (
          <span className="infinite">∞</span>
        ) : (
          noData ? (
            <span className="no-data"> - </span>
          ) : (
            <span>{value > 0 ? '+' : ''}{value}%</span>
          )
        )}

        {
          (!noData && value < 0) &&
          (<ArrowDownOutlined style={{fontSize: 16, color: Color.SUCCESS}}/>)
        }

        {
          (!noData && (infinite || value >= 0)) &&
          (<ArrowUpOutlined style={{fontSize: 16, color: Color.DANGER}}/>)
        }

      </span>
    )
  }
}
